// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/bridge/query/:table': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bridge/query/[table].get').default>>>>
    }
    '/api/bridge/session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bridge/session.post').default>>>>
    }
    '/api/bridge/templates': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bridge/templates.get').default>>>>
    }
    '/api/bridge/templates/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bridge/templates/[id].get').default>>>>
    }
    '/api/session/composer-payload': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session/composer-payload.get').default>>>>
    }
    '/api/session/composer-save': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session/composer-save.post').default>>>>
    }
    '/api/session/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session/generate.post').default>>>>
    }
    '/api/session/preview': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session/preview.post').default>>>>
    }
    '/api/session/themes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/session/themes.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}