-- =============================================================================
-- Evidence Sources (DB) and Techniques (DB) - Lens-Ready Schema
-- =============================================================================
-- These tables enable the "lens" system: same techniques can be explained
-- through Western, TCM, or Hybrid frameworks.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Evidence Sources (DB)
-- -----------------------------------------------------------------------------
-- Stores research, guidelines, and traditional references that support techniques
-- Enables evidence-based explanations while honoring traditional knowledge

CREATE TABLE IF NOT EXISTS "evidence_sources" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  
  -- Core identification
  "evidence_source" TEXT NOT NULL,  -- Title
  "evidence_type" TEXT,  -- Systematic Review, Meta-analysis, RCT, Observational, Mechanistic, Clinical Guideline, Traditional/Lineage, Expert Consensus
  
  -- Domain relations (stored as Notion page IDs or comma-separated)
  "primary_domain" TEXT,  -- -> Attribute Taxonomy (L1)
  "secondary_domains" TEXT,  -- -> Attribute Taxonomy (NL)
  
  -- Application relations
  "applies_to_techniques" TEXT,  -- <-> Techniques (NL) - bidirectional
  "applies_to_protocols" TEXT,  -- <-> Nutrition Protocols (NL)
  "applies_to_supplement_interactions" TEXT,  -- <-> Supplement Interactions (NL)
  
  -- Lens system
  "lens_tags" TEXT,  -- Multi-select: Western, TCM, Hybrid, Somatic, Breathwork, Movement, Sleep
  
  -- Citation info
  "citation_apa_short" TEXT,
  "doi_url" TEXT,
  "year" INTEGER,
  "author_organisation" TEXT,
  "key_claims_summary" TEXT,  -- One paragraph only
  
  -- Verification workflow
  "evidence_confidence" TEXT,  -- Strong, Moderate, Emerging, Traditional
  "review_state" TEXT,  -- Unreviewed, In Review, Verified, Disputed, Deprecated
  "verified_by" TEXT,  -- -> Professional Profiles (L1)
  "verification_notes" TEXT,
  "last_reviewed_date" DATE,
  
  "notes" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

-- Index for common queries
CREATE INDEX IF NOT EXISTS "idx_evidence_sources_type" ON "evidence_sources" ("evidence_type");
CREATE INDEX IF NOT EXISTS "idx_evidence_sources_confidence" ON "evidence_sources" ("evidence_confidence");
CREATE INDEX IF NOT EXISTS "idx_evidence_sources_lens" ON "evidence_sources" ("lens_tags");


-- -----------------------------------------------------------------------------
-- Techniques (DB)
-- -----------------------------------------------------------------------------
-- The core technique library with lens-specific explanation templates
-- This is where the multi-paradigm magic happens

CREATE TABLE IF NOT EXISTS "techniques" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  
  -- Core identification
  "technique" TEXT NOT NULL,  -- Title
  "technique_category" TEXT,  -- Breath, Movement, Somatic, Meditation/NSDR, Tapping, Cognitive, Ritual
  "objective" TEXT,  -- Multi-select: Downshift Arousal, Increase Energy, Improve Sleep, etc.
  
  -- Intent relations (stored as Notion page IDs or comma-separated)
  "primary_intent" TEXT,  -- -> Attribute Taxonomy (L1)
  "secondary_intents" TEXT,  -- -> Attribute Taxonomy (NL)
  
  -- LENS SYSTEM - The key innovation
  "lens_availability" TEXT,  -- Multi-select: Western, TCM, Hybrid
  "lens_explanation_western" TEXT,  -- Short reusable paragraph template
  "lens_explanation_tcm" TEXT,  -- Short reusable paragraph template
  "mechanism_notes_simple" TEXT,  -- Plain explanation (no medical claims)
  
  -- Safety
  "contraindications_summary" TEXT,  -- -> Safety Rules (NL)
  
  -- Session configuration
  "required_inputs" TEXT,  -- Multi-select: Duration, Intensity, Experience Level, Contraindications Check, Environment
  "default_duration_min" INTEGER,
  "intensity_band" TEXT,  -- Low, Medium, High
  
  -- Relations
  "session_compatibility" TEXT,  -- <-> Session Templates (NL)
  "evidence_sources" TEXT,  -- <-> Evidence Sources (NL) - bidirectional
  
  "notes" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

-- Index for common queries
CREATE INDEX IF NOT EXISTS "idx_techniques_category" ON "techniques" ("technique_category");
CREATE INDEX IF NOT EXISTS "idx_techniques_lens" ON "techniques" ("lens_availability");
CREATE INDEX IF NOT EXISTS "idx_techniques_intensity" ON "techniques" ("intensity_band");


-- -----------------------------------------------------------------------------
-- Seed Data: Evidence Sources
-- -----------------------------------------------------------------------------

INSERT INTO "evidence_sources" (
  "evidence_source", "evidence_type", "primary_domain", "secondary_domains",
  "applies_to_techniques", "lens_tags", "citation_apa_short", "doi_url",
  "year", "key_claims_summary", "evidence_confidence", "review_state", "notes"
) VALUES 
(
  'NSDR / Yoga Nidra research overview',
  'Observational',
  'Sleep Regulation',
  'Cognitive Load Capacity',
  'NSDR (Non-Sleep Deep Rest)',
  'Western;Sleep',
  'Author/year placeholder - replace with chosen paper list later',
  'https://',
  2020,
  'Brief summary: NSDR/Nidra associated with downregulation, perceived stress reduction, and relaxation response.',
  'Emerging',
  'Unreviewed',
  'Used for demo of "Western lens explanation"'
),
(
  'Breathwork safety considerations',
  'Clinical Guideline',
  'Recovery Capacity',
  'Injury Risk Modulation',
  'Wim Hof Basic (Beginner-safe)',
  'Western;Breathwork',
  'Author/year placeholder - add guideline link',
  'https://',
  2018,
  'Brief summary: flags contraindications for breath holds/intense practices; outlines safe participation.',
  'Moderate',
  'Unreviewed',
  'Anchors safety-first narrative in session generation'
),
(
  'TCM Liver Qi stagnation (lineage/overview)',
  'Traditional/Lineage',
  'Inflammatory Modulation',
  'Cognitive Load Capacity',
  'TCM Liver Flow Qigong (Beginner)',
  'TCM;Movement',
  'Lineage reference placeholder - replace with chosen text/source',
  'https://',
  2005,
  'Brief summary: frames mood/irritability/tension patterns and movement/breath approaches; non-medical language.',
  'Traditional',
  'Unreviewed',
  'Demo of "TCM lens explanation"'
),
(
  'Vitamin D + K2 cofactor rationale',
  'Mechanistic',
  'Metabolic Regulation',
  'Recovery Capacity',
  NULL,  -- No technique link
  'Western',
  'Narrative placeholder; add DOI later',
  'https://',
  2017,
  'Brief summary: K2 supports calcium handling pathways and is commonly paired with D; avoid overclaiming.',
  'Emerging',
  'Unreviewed',
  'Demo of supplement explanation + caution'
);


-- -----------------------------------------------------------------------------
-- Seed Data: Techniques
-- -----------------------------------------------------------------------------

INSERT INTO "techniques" (
  "technique", "technique_category", "objective", "primary_intent", "secondary_intents",
  "lens_availability", "lens_explanation_western", "lens_explanation_tcm",
  "mechanism_notes_simple", "required_inputs", "default_duration_min",
  "intensity_band", "evidence_sources", "notes"
) VALUES 
(
  'NSDR (Non-Sleep Deep Rest)',
  'Meditation/NSDR',
  'Downshift Arousal;Improve Sleep',
  'Sleep Regulation',
  'Cognitive Load Capacity',
  'Western;Hybrid',
  'This practice shifts attention inward, reduces cognitive load, and supports parasympathetic settling. Expect calmer breathing, reduced mental chatter, and easier transition into rest.',
  'In TCM language, this supports Shen settling and smooths overactive mind activity; keep gentle, consistent, and avoid forcing.',
  'Low-demand guided rest state; suitable for beginners.',
  'Duration;Environment',
  15,
  'Low',
  'NSDR / Yoga Nidra research overview',
  'Start with this as the flagship "lens demo"'
),
(
  'EFT Tapping (basic sequence)',
  'Tapping',
  'Reduce Anxiety;Release Tension',
  'Inhibitory Control',
  'Emotional Regulation',
  'Western;Hybrid',
  'Rhythmic tapping combined with attention on the issue can reduce perceived stress and interrupt rumination loops.',
  'Can be framed as calming overactive Shen and supporting smooth Qi movement while attention stays anchored.',
  'Somatic rhythm + attention anchor; keep language non-claiming.',
  'Duration;Experience Level',
  10,
  'Low',
  NULL,
  'Add evidence later; keep for demo of "somatic lens"'
),
(
  'Wim Hof Basic (Beginner-safe)',
  'Breath',
  'Increase Energy;Improve Focus',
  'Recovery Capacity',
  'Cognitive Load Capacity',
  'Western',
  'Breathing rounds change CO2 tolerance and perceived arousal; keep it gentle, stop on dizziness, and never practice in water.',
  NULL,  -- No TCM explanation for this one
  'Breath pacing; focus on safety and gradual progression.',
  'Duration;Experience Level;Contraindications Check',
  12,
  'Medium',
  'Breathwork safety considerations',
  'Keep "safety first" demonstration'
),
(
  'TCM Liver Flow Qigong (Beginner)',
  'Movement',
  'Release Tension;Reduce Anxiety',
  'Inflammatory Modulation',
  'Cognitive Load Capacity',
  'TCM;Hybrid',
  'Gentle movement + breathing can reduce muscle guarding and support a calmer baseline.',
  'Supports Liver Qi flow: smooth movement, soft eyes, relaxed ribs; avoid strain and keep breath easy.',
  'Gentle mobility + breath synchrony; good for tension patterns.',
  'Duration;Intensity',
  15,
  'Low',
  'TCM Liver Qi stagnation (lineage/overview)',
  'Demo of explicit TCM lens output'
);


-- -----------------------------------------------------------------------------
-- Demo Session Template: Hybrid Lens Demo (Movement -> NSDR)
-- -----------------------------------------------------------------------------
-- This is a pre-built session that demonstrates the lens system

INSERT INTO "session_templates" (
  "column_name", "type", "default_duration__min_", 
  "primary_intent____l1_", "secondary_intents____nl_",
  "script_strictness", "notes"
) VALUES (
  'Hybrid Lens Demo: Movement to Rest',
  'Hybrid',
  30,
  'Sleep Regulation',
  'Inflammatory Modulation;Cognitive Load Capacity',
  'Flexible',
  'Flagship demo session: TCM Liver Flow Qigong (15min) -> NSDR (15min). Use to test lens-switching in session generation.'
);

