-- Run this in Supabase SQL Editor to fix the 3 failed tables:

-- Drop the old tables first
DROP TABLE IF EXISTS "programme_profiles";
DROP TABLE IF EXISTS "breath_library";
DROP TABLE IF EXISTS "symbols_index";

-- programme_profiles (14 rows)
CREATE TABLE IF NOT EXISTS "programme_profiles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "session_templates__db____relation___session_templates__db___if_" TEXT,
  "default_strictness___select" TEXT,
  "primary_doctrine___select" TEXT,
  "enabled_blocks___relation___dashboard_blocks__db_" TEXT,
  "secondary_attribute_focus___relation___attribute_taxonomy__db_" TEXT,
  "dashboard_blocks__db____relation___dashboard_blocks__db___if_pr" TEXT,
  "default_depth___select" TEXT,
  "notes___text" TEXT,
  "primary_attribute_focus___relation___attribute_taxonomy__db_" TEXT,
  "programme_profile___title" TEXT
);

-- breath_library (26 rows)
CREATE TABLE IF NOT EXISTS "breath_library" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "typical_use" TEXT,
  "notes" TEXT,
  "core_breath_quality" TEXT,
  "activation_level" TEXT,
  "primary_element" TEXT,
  "safety_tier" TEXT,
  "untitled_database" TEXT,
  "organ___systemprimary_emotionsecondary_emotionstress_expression" TEXT,
  "safety_rules" TEXT,
  "contraindications" TEXT,
  "programme_profiles__db___" TEXT,
  "secondary_element" TEXT,
  "chakra_systems__db_" TEXT,
  "protocol_name" TEXT
);

-- symbols_index (94 rows)
CREATE TABLE IF NOT EXISTS "symbols_index" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "cultural_scope" TEXT,
  "organ___systemprimary_emotionsecondary_emotionstress_expression" TEXT,
  "sacred_geometry" TEXT,
  "secondary_element" TEXT,
  "untitled_database" TEXT,
  "programme_profiles__db___" TEXT,
  "primary_element" TEXT,
  "archetypal_personas__db_" TEXT,
  "meaning_domain" TEXT,
  "stones" TEXT,
  "emotional_tone" TEXT,
  "mythology" TEXT,
  "symbol_class" TEXT,
  "nadi_system__db_" TEXT,
  "chakra_systems__db_" TEXT,
  "astrological_archetype" TEXT,
  "sacred_animal" TEXT,
  "symbol" TEXT,
  "notes" TEXT
);



