-- =============================================================================
-- LENS REGISTRY - Safe Version (handles existing data)
-- =============================================================================
-- Run this if you get duplicate key errors
-- Uses ON CONFLICT to skip or update existing rows
-- =============================================================================

-- Create tables if they don't exist
CREATE TABLE IF NOT EXISTS "lens_definitions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lens_slug" TEXT UNIQUE NOT NULL,
  "lens_name" TEXT NOT NULL,
  "lens_description" TEXT,
  "paradigm_family" TEXT,
  "language_style" TEXT,
  "cultural_origin" TEXT,
  "is_system" BOOLEAN DEFAULT TRUE,
  "is_active" BOOLEAN DEFAULT TRUE,
  "created_by" TEXT,
  "icon" TEXT,
  "color" TEXT,
  "sort_order" INTEGER DEFAULT 100,
  "notes" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "technique_lens_explanations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "technique_id" BIGINT REFERENCES "techniques"("id") ON DELETE CASCADE,
  "lens_id" BIGINT REFERENCES "lens_definitions"("id") ON DELETE CASCADE,
  "explanation_template" TEXT NOT NULL,
  "mechanism_notes" TEXT,
  "cue_language" TEXT,
  "safety_framing" TEXT,
  "is_verified" BOOLEAN DEFAULT FALSE,
  "verified_by" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE("technique_id", "lens_id")
);

CREATE TABLE IF NOT EXISTS "user_lens_preferences" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "lens_id" BIGINT REFERENCES "lens_definitions"("id") ON DELETE CASCADE,
  "preference_level" INTEGER DEFAULT 50,
  "is_enabled" BOOLEAN DEFAULT TRUE,
  "last_used_at" TIMESTAMPTZ,
  "use_count" INTEGER DEFAULT 0,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE("user_id", "lens_id")
);

CREATE TABLE IF NOT EXISTS "user_lens_context" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "context_date" DATE NOT NULL,
  "mood_state" TEXT,
  "energy_level" INTEGER,
  "receptivity" TEXT,
  "recent_lenses_used" TEXT,
  "ai_suggested_lens" TEXT,
  "ai_reasoning" TEXT,
  "override_lens" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE("user_id", "context_date")
);

-- Insert lenses with ON CONFLICT DO NOTHING (skip if exists)
INSERT INTO "lens_definitions" (
  "lens_slug", "lens_name", "lens_description", "paradigm_family", 
  "language_style", "cultural_origin", "icon", "color", "sort_order"
) VALUES 
('western', 'Western Scientific', 
 'Evidence-based, mechanistic explanations grounded in physiology and neuroscience.',
 'scientific', 'clinical', 'western', '🔬', '#3B82F6', 10),
('clinical', 'Clinical/Medical', 
 'More technical terminology suitable for healthcare professionals.',
 'scientific', 'clinical', 'western', '🏥', '#1D4ED8', 11),
('athletic', 'Athletic/Performance', 
 'Frames practices in terms of performance optimization and recovery.',
 'performance', 'direct', 'modern', '🏃', '#10B981', 12),
('tcm', 'Traditional Chinese Medicine', 
 'Frames practices using Qi, meridians, and Five Element theory.',
 'traditional', 'poetic', 'eastern', '☯️', '#DC2626', 20),
('ayurvedic', 'Ayurvedic', 
 'Uses Dosha theory (Vata, Pitta, Kapha) and Ayurvedic principles.',
 'traditional', 'warm', 'eastern', '🕉️', '#F59E0B', 21),
('yogic', 'Yogic/Tantric', 
 'Chakras, Nadis, Kundalini. Classical yoga philosophy framework.',
 'traditional', 'poetic', 'eastern', '🧘', '#8B5CF6', 22),
('somatic', 'Somatic/Body-Based', 
 'Emphasizes felt sense, body awareness, nervous system regulation.',
 'somatic', 'warm', 'modern', '🫀', '#EC4899', 30),
('polyvagal', 'Polyvagal-Informed', 
 'Uses vagal tone, ventral/dorsal states, neuroception.',
 'somatic', 'warm', 'modern', '🌊', '#06B6D4', 31),
('spiritual', 'Spiritual/Energetic', 
 'References energy, consciousness, presence. Non-denominational.',
 'spiritual', 'poetic', 'universal', '✨', '#A855F7', 40),
('contemplative', 'Contemplative/Mindfulness', 
 'Secular mindfulness language. Attention, awareness, present moment.',
 'spiritual', 'minimal', 'universal', '🪷', '#14B8A6', 41),
('plain', 'Plain Language', 
 'Simple, accessible explanations. No jargon, no frameworks.',
 'practical', 'direct', 'universal', '💬', '#6B7280', 50),
('motivational', 'Motivational/Coaching', 
 'Encouraging, action-oriented language. Focuses on growth.',
 'practical', 'warm', 'modern', '🎯', '#F97316', 51),
('hybrid', 'Hybrid/Adaptive', 
 'Blends multiple lenses based on context. AI selects optimal combination.',
 'adaptive', 'adaptive', 'universal', '🔄', '#6366F1', 0),
('personalized', 'Personalized', 
 'User-defined lens combining preferred elements from multiple frameworks.',
 'adaptive', 'adaptive', 'universal', '👤', '#8B5CF6', 1)
ON CONFLICT (lens_slug) DO NOTHING;

-- Create indexes if they don't exist
CREATE INDEX IF NOT EXISTS "idx_lens_definitions_slug" ON "lens_definitions" ("lens_slug");
CREATE INDEX IF NOT EXISTS "idx_lens_definitions_active" ON "lens_definitions" ("is_active");
CREATE INDEX IF NOT EXISTS "idx_technique_lens_technique" ON "technique_lens_explanations" ("technique_id");
CREATE INDEX IF NOT EXISTS "idx_technique_lens_lens" ON "technique_lens_explanations" ("lens_id");
CREATE INDEX IF NOT EXISTS "idx_user_lens_pref_user" ON "user_lens_preferences" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_user_lens_context_user" ON "user_lens_context" ("user_id", "context_date");

-- Success message
SELECT 'Lens registry tables created/updated successfully. ' || 
       (SELECT COUNT(*) FROM lens_definitions) || ' lenses in system.' AS status;




