-- =============================================================================
-- LENS REGISTRY - Flexible, Infinite Lens Architecture
-- =============================================================================
-- This replaces hard-coded lenses with a registry pattern that supports:
-- - Predefined system lenses (Western, TCM, Ayurvedic, etc.)
-- - User-created custom lenses
-- - AI-selected lens blending based on context
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Lens Definitions (The Registry)
-- -----------------------------------------------------------------------------
-- Defines all available explanatory frameworks
-- System lenses are is_system=true, user lenses are is_system=false

CREATE TABLE IF NOT EXISTS "lens_definitions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lens_slug" TEXT UNIQUE NOT NULL,  -- 'western', 'tcm', 'ayurvedic', etc.
  "lens_name" TEXT NOT NULL,  -- Display name
  "lens_description" TEXT,  -- What this lens represents
  "paradigm_family" TEXT,  -- 'scientific', 'traditional', 'somatic', 'spiritual', 'performance'
  "language_style" TEXT,  -- 'clinical', 'poetic', 'direct', 'warm', 'minimal'
  "cultural_origin" TEXT,  -- 'western', 'eastern', 'indigenous', 'modern', 'universal'
  "is_system" BOOLEAN DEFAULT TRUE,  -- System-provided or user-created
  "is_active" BOOLEAN DEFAULT TRUE,
  "created_by" TEXT,  -- User ID if user-created
  "icon" TEXT,  -- Emoji or icon reference
  "color" TEXT,  -- Theme color for UI
  "sort_order" INTEGER DEFAULT 100,
  "notes" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- Technique Lens Explanations (Many-to-Many)
-- -----------------------------------------------------------------------------
-- Each technique can have explanations in multiple lenses
-- This allows infinite lenses without schema changes

CREATE TABLE IF NOT EXISTS "technique_lens_explanations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "technique_id" BIGINT REFERENCES "techniques"("id") ON DELETE CASCADE,
  "lens_id" BIGINT REFERENCES "lens_definitions"("id") ON DELETE CASCADE,
  "explanation_template" TEXT NOT NULL,  -- The lens-specific explanation
  "mechanism_notes" TEXT,  -- Optional mechanism in this lens's language
  "cue_language" TEXT,  -- How to phrase cues in this lens
  "safety_framing" TEXT,  -- How to frame safety in this lens
  "is_verified" BOOLEAN DEFAULT FALSE,
  "verified_by" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE("technique_id", "lens_id")
);

-- -----------------------------------------------------------------------------
-- User Lens Preferences
-- -----------------------------------------------------------------------------
-- Tracks which lenses a user prefers/has access to

CREATE TABLE IF NOT EXISTS "user_lens_preferences" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "lens_id" BIGINT REFERENCES "lens_definitions"("id") ON DELETE CASCADE,
  "preference_level" INTEGER DEFAULT 50,  -- 0-100, how much they prefer this lens
  "is_enabled" BOOLEAN DEFAULT TRUE,
  "last_used_at" TIMESTAMPTZ,
  "use_count" INTEGER DEFAULT 0,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE("user_id", "lens_id")
);

-- -----------------------------------------------------------------------------
-- AI Lens Context (For Adaptive Selection)
-- -----------------------------------------------------------------------------
-- Stores context that informs AI lens selection

CREATE TABLE IF NOT EXISTS "user_lens_context" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "context_date" DATE NOT NULL,
  "mood_state" TEXT,  -- Current mood from check-in
  "energy_level" INTEGER,  -- 1-10
  "receptivity" TEXT,  -- 'high', 'medium', 'low' - openness to different frameworks
  "recent_lenses_used" TEXT,  -- JSON array of recent lens slugs
  "ai_suggested_lens" TEXT,  -- What AI would suggest
  "ai_reasoning" TEXT,  -- Why AI suggested this
  "override_lens" TEXT,  -- If user explicitly chose different
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE("user_id", "context_date")
);

-- -----------------------------------------------------------------------------
-- SEED: System Lenses (Predefined)
-- -----------------------------------------------------------------------------

INSERT INTO "lens_definitions" (
  "lens_slug", "lens_name", "lens_description", "paradigm_family", 
  "language_style", "cultural_origin", "icon", "color", "sort_order"
) VALUES 
-- Scientific/Western
('western', 'Western Scientific', 
 'Evidence-based, mechanistic explanations grounded in physiology and neuroscience. Uses clinical language without medical claims.',
 'scientific', 'clinical', 'western', '🔬', '#3B82F6', 10),

('clinical', 'Clinical/Medical', 
 'More technical terminology suitable for healthcare professionals or users comfortable with medical language.',
 'scientific', 'clinical', 'western', '🏥', '#1D4ED8', 11),

('athletic', 'Athletic/Performance', 
 'Frames practices in terms of performance optimization, recovery, and training adaptation.',
 'performance', 'direct', 'modern', '🏃', '#10B981', 12),

-- Traditional Eastern
('tcm', 'Traditional Chinese Medicine', 
 'Frames practices using Qi, meridians, organ systems, and Five Element theory. Non-medical language.',
 'traditional', 'poetic', 'eastern', '☯️', '#DC2626', 20),

('ayurvedic', 'Ayurvedic', 
 'Uses Dosha theory (Vata, Pitta, Kapha), Prana, and Ayurvedic principles. Sanskrit terms where appropriate.',
 'traditional', 'warm', 'eastern', '🕉️', '#F59E0B', 21),

('yogic', 'Yogic/Tantric', 
 'Chakras, Nadis, Kundalini, Pratyahara. Classical yoga philosophy framework.',
 'traditional', 'poetic', 'eastern', '🧘', '#8B5CF6', 22),

-- Somatic/Body-Based
('somatic', 'Somatic/Body-Based', 
 'Emphasizes felt sense, body awareness, nervous system regulation. Trauma-informed language.',
 'somatic', 'warm', 'modern', '🫀', '#EC4899', 30),

('polyvagal', 'Polyvagal-Informed', 
 'Uses vagal tone, ventral/dorsal states, neuroception. Focuses on safety and co-regulation.',
 'somatic', 'warm', 'modern', '🌊', '#06B6D4', 31),

-- Spiritual/Metaphysical
('spiritual', 'Spiritual/Energetic', 
 'References energy, consciousness, presence, connection. Non-denominational spiritual language.',
 'spiritual', 'poetic', 'universal', '✨', '#A855F7', 40),

('contemplative', 'Contemplative/Mindfulness', 
 'Secular mindfulness language. Attention, awareness, present moment, non-judgment.',
 'spiritual', 'minimal', 'universal', '🪷', '#14B8A6', 41),

-- Practical/Simple
('plain', 'Plain Language', 
 'Simple, accessible explanations. No jargon, no frameworks. Just what to do and why it helps.',
 'practical', 'direct', 'universal', '💬', '#6B7280', 50),

('motivational', 'Motivational/Coaching', 
 'Encouraging, action-oriented language. Focuses on growth, progress, and self-improvement.',
 'practical', 'warm', 'modern', '🎯', '#F97316', 51),

-- Hybrid/Blended (AI-selected)
('hybrid', 'Hybrid/Adaptive', 
 'Blends multiple lenses based on context. AI selects optimal combination for user state.',
 'adaptive', 'adaptive', 'universal', '🔄', '#6366F1', 0),

('personalized', 'Personalized', 
 'User-defined lens combining preferred elements from multiple frameworks.',
 'adaptive', 'adaptive', 'universal', '👤', '#8B5CF6', 1);


-- -----------------------------------------------------------------------------
-- SEED: Technique Explanations for Each Lens
-- -----------------------------------------------------------------------------
-- NSDR technique across multiple lenses

INSERT INTO "technique_lens_explanations" (
  "technique_id", "lens_id", "explanation_template", "mechanism_notes"
) 
SELECT 
  t.id,
  l.id,
  CASE l.lens_slug
    WHEN 'western' THEN 'This practice shifts attention inward, reduces cognitive load, and supports parasympathetic settling. Expect calmer breathing, reduced mental chatter, and easier transition into rest.'
    WHEN 'clinical' THEN 'Non-Sleep Deep Rest induces a hypnagogic state with maintained awareness, reducing cortical activation and sympathetic tone. Associated with enhanced neuroplasticity markers post-session.'
    WHEN 'athletic' THEN 'NSDR accelerates recovery by downregulating the stress response. Use post-training or during high-load phases to optimize adaptation. 20 minutes NSDR ≈ supplementary recovery.'
    WHEN 'tcm' THEN 'In TCM language, this supports Shen settling and smooths overactive mind activity. Calms the Heart, nourishes Yin, and allows Qi to descend. Keep gentle, consistent, and avoid forcing.'
    WHEN 'ayurvedic' THEN 'This practice pacifies Vata dosha and calms Prana Vayu. Ideal for Vata imbalances (anxiety, restlessness, insomnia). Creates space for Ojas to rebuild.'
    WHEN 'yogic' THEN 'Yoga Nidra draws awareness through the koshas, from gross to subtle body. Pratyahara (sense withdrawal) naturally arises. The witness consciousness (Sakshi) observes without attachment.'
    WHEN 'somatic' THEN 'Allow your body to find its own rhythm. Notice any sensations without trying to change them. Your nervous system knows how to settle when given permission. This is about being, not doing.'
    WHEN 'polyvagal' THEN 'This practice supports ventral vagal engagement through gentle awareness. As safety cues increase, the system naturally shifts from mobilization to rest-and-digest. Co-regulate with the guidance.'
    WHEN 'spiritual' THEN 'Rest in awareness itself. Allow thoughts to arise and dissolve like clouds in sky. You are not your thoughts—you are the space in which they appear. Return to presence.'
    WHEN 'contemplative' THEN 'Settle into open awareness. Notice whatever arises—sensations, thoughts, feelings—without judgment or engagement. Simply observe. Return to the breath when needed.'
    WHEN 'plain' THEN 'Lie down comfortably. Follow the guidance. Let your mind wander if it wants to—that is fine. You will likely feel more rested afterward, even if you do not sleep.'
    WHEN 'motivational' THEN 'This is your reset button. 20 minutes of NSDR can restore what a poor night of sleep took away. You are investing in your recovery, focus, and resilience. Let go and recover.'
    ELSE 'Follow the practice with gentle attention.'
  END,
  CASE l.lens_slug
    WHEN 'western' THEN 'Activates parasympathetic nervous system via attention redirection'
    WHEN 'clinical' THEN 'Theta wave predominance with maintained alpha; reduced DMN activity'
    WHEN 'athletic' THEN 'HRV improvement, cortisol reduction, glycogen sparing'
    WHEN 'tcm' THEN 'Settles Shen, nourishes Heart Yin, descends Qi'
    WHEN 'ayurvedic' THEN 'Vata pacification, Prana regulation, Ojas restoration'
    WHEN 'yogic' THEN 'Pratyahara leading to Dharana; kosha awareness'
    WHEN 'somatic' THEN 'Nervous system regulation through interoceptive awareness'
    WHEN 'polyvagal' THEN 'Ventral vagal engagement via safety cues'
    WHEN 'spiritual' THEN 'Dissolution of thought-identification; presence'
    WHEN 'contemplative' THEN 'Non-reactive awareness; present-moment attention'
    WHEN 'plain' THEN 'Rest without sleeping; feel better after'
    WHEN 'motivational' THEN 'Recovery accelerator; mental reset'
    ELSE NULL
  END
FROM "techniques" t
CROSS JOIN "lens_definitions" l
WHERE t.technique = 'NSDR (Non-Sleep Deep Rest)'
AND l.lens_slug NOT IN ('hybrid', 'personalized');


-- TCM Qigong across multiple lenses
INSERT INTO "technique_lens_explanations" (
  "technique_id", "lens_id", "explanation_template", "mechanism_notes"
) 
SELECT 
  t.id,
  l.id,
  CASE l.lens_slug
    WHEN 'western' THEN 'Gentle movement combined with breathing reduces muscle tension and supports a calmer baseline. Slow, rhythmic motion activates the relaxation response.'
    WHEN 'clinical' THEN 'Low-intensity movement with diaphragmatic breathing reduces muscular hypertonicity and modulates autonomic balance toward parasympathetic predominance.'
    WHEN 'athletic' THEN 'Active recovery movement. Promotes blood flow, reduces DOMS, and maintains mobility without adding training stress. Ideal for rest days or post-session cooldown.'
    WHEN 'tcm' THEN 'Supports Liver Qi flow: smooth movement, soft eyes, relaxed ribs. Avoid strain and keep breath easy. Releases stagnation that manifests as irritability or tension.'
    WHEN 'ayurvedic' THEN 'Flowing movement pacifies Vata while the warming quality addresses Kapha stagnation. Pitta types should practice slowly to avoid overheating. Balances Prana and Apana.'
    WHEN 'yogic' THEN 'Moving meditation that cultivates Prana flow through the Nadis. Gentle spinal movements activate Sushumna. Awareness follows breath and movement as one.'
    WHEN 'somatic' THEN 'Move slowly enough to feel. Notice where you hold tension. Let the movement be curious, not corrective. Your body knows what it needs—follow its lead.'
    WHEN 'polyvagal' THEN 'Slow, rhythmic movement with breath provides neural exercise for the vagal brake. Orienting through gentle head/eye movements supports neuroception of safety.'
    WHEN 'spiritual' THEN 'Moving prayer. Each gesture is an offering, each breath a conversation with the life force. Let the practice move you rather than you moving through it.'
    WHEN 'contemplative' THEN 'Bring full attention to the sensations of movement. When the mind wanders, return to the felt sense of the body in motion. Movement as meditation.'
    WHEN 'plain' THEN 'Gentle stretching and movement with breathing. Move slowly, do not force anything. You should feel more relaxed and less tense afterward.'
    WHEN 'motivational' THEN 'Movement is medicine. This gentle flow releases tension you did not know you were holding. Each session builds your body''s capacity to handle stress.'
    ELSE 'Move gently with awareness.'
  END,
  CASE l.lens_slug
    WHEN 'tcm' THEN 'Smooths Liver Qi, releases Wood element stagnation'
    WHEN 'ayurvedic' THEN 'Vata-Kapha balancing; Prana-Apana harmonization'
    WHEN 'yogic' THEN 'Nadi purification; Prana cultivation'
    WHEN 'somatic' THEN 'Interoceptive awareness; tension release'
    WHEN 'polyvagal' THEN 'Vagal toning through rhythmic movement'
    ELSE 'Gentle mobility and nervous system regulation'
  END
FROM "techniques" t
CROSS JOIN "lens_definitions" l
WHERE t.technique = 'TCM Liver Flow Qigong (Beginner)'
AND l.lens_slug NOT IN ('hybrid', 'personalized');


-- -----------------------------------------------------------------------------
-- Indexes for Performance
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS "idx_lens_definitions_slug" ON "lens_definitions" ("lens_slug");
CREATE INDEX IF NOT EXISTS "idx_lens_definitions_active" ON "lens_definitions" ("is_active");
CREATE INDEX IF NOT EXISTS "idx_technique_lens_technique" ON "technique_lens_explanations" ("technique_id");
CREATE INDEX IF NOT EXISTS "idx_technique_lens_lens" ON "technique_lens_explanations" ("lens_id");
CREATE INDEX IF NOT EXISTS "idx_user_lens_pref_user" ON "user_lens_preferences" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_user_lens_context_user" ON "user_lens_context" ("user_id", "context_date");




