-- =============================================================================
-- META-INTELLIGENCE LAYER - Adaptive Scope, Depth, and Collective Wisdom
-- =============================================================================
-- This layer enables AI to:
-- 1. ZOOM IN/OUT - Narrow specialist focus OR widen to cross-domain insights
-- 2. SURFACE/DEEP - Behavioral adjustments OR fundamental restructuring
-- 3. INDIVIDUAL/COLLECTIVE - User patterns OR aggregate wisdom across users
-- 4. ESTABLISHED/EXPERIMENTAL - Evidence-based OR frontier exploration
-- 
-- All with explicit consent and transparency flags
-- =============================================================================

-- -----------------------------------------------------------------------------
-- SCOPE DIMENSION (Narrow ↔ Wide)
-- -----------------------------------------------------------------------------
-- AI can operate at different scopes:
-- NARROW: Deep expertise in one domain (e.g., "only breathwork")
-- MEDIUM: Related domains (e.g., "breathwork + movement")
-- WIDE: Cross-domain synthesis (e.g., "athletic techniques for anxiety")
-- UNIVERSAL: Draw from any field (e.g., "what works in addiction for grief")

CREATE TABLE IF NOT EXISTS "ai_scope_levels" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "scope_slug" TEXT UNIQUE NOT NULL,
  "scope_name" TEXT NOT NULL,
  "description" TEXT,
  "example_use" TEXT,
  "risk_level" TEXT,  -- 'low', 'medium', 'high'
  "requires_consent" BOOLEAN DEFAULT FALSE,
  "sort_order" INTEGER
);

INSERT INTO "ai_scope_levels" ("scope_slug", "scope_name", "description", "example_use", "risk_level", "requires_consent", "sort_order")
VALUES
('narrow', 'Narrow/Specialist', 
 'AI stays within a single domain. Deep expertise, minimal cross-pollination.',
 'User wants only TCM-based approaches. AI stays in that lane.',
 'low', FALSE, 1),

('focused', 'Focused/Related', 
 'AI draws from closely related domains. Breathwork + meditation, for example.',
 'User doing breathwork, AI might suggest complementary body awareness.',
 'low', FALSE, 2),

('medium', 'Medium/Adjacent', 
 'AI draws from adjacent fields. Athletic training insights for stress.',
 'User stressed at work, AI suggests recovery techniques from sports science.',
 'low', FALSE, 3),

('wide', 'Wide/Cross-Domain', 
 'AI synthesizes across different domains. Finds unexpected connections.',
 'User resistant to therapy, AI pulls from contemplative traditions instead.',
 'medium', FALSE, 4),

('universal', 'Universal/Synthesis', 
 'AI can draw from any field, including experimental and user-generated.',
 'User has tried everything, AI explores unconventional combinations.',
 'high', TRUE, 5),

('experimental', 'Experimental/Frontier', 
 'AI explores beyond established practice. Beta testing, novel combinations.',
 'User consents to trying something new that hasnt been validated yet.',
 'high', TRUE, 6);


-- -----------------------------------------------------------------------------
-- DEPTH DIMENSION (Surface ↔ Deep)
-- -----------------------------------------------------------------------------
-- AI can work at different depths:
-- SURFACE: Immediate behavioral/practical interventions
-- PATTERN: Working with recurring patterns
-- STRUCTURAL: Underlying beliefs, schemas, identity
-- FOUNDATIONAL: Core self-concept, existential, transformational

CREATE TABLE IF NOT EXISTS "ai_depth_levels" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "depth_slug" TEXT UNIQUE NOT NULL,
  "depth_name" TEXT NOT NULL,
  "description" TEXT,
  "example_work" TEXT,
  "requires_professional" BOOLEAN DEFAULT FALSE,
  "requires_consent" BOOLEAN DEFAULT FALSE,
  "safety_notes" TEXT,
  "sort_order" INTEGER
);

INSERT INTO "ai_depth_levels" ("depth_slug", "depth_name", "description", "example_work", "requires_professional", "requires_consent", "safety_notes", "sort_order")
VALUES
('surface', 'Surface/Behavioral', 
 'Immediate, practical interventions. What to do right now.',
 'Breathing exercise for acute stress. Sleep hygiene tips.',
 FALSE, FALSE, 'Safe for all users', 1),

('habit', 'Habit/Practice', 
 'Building consistent practices over time. Skill development.',
 'Establishing morning routine. Developing meditation habit.',
 FALSE, FALSE, 'Safe for all users', 2),

('pattern', 'Pattern/Recurring', 
 'Identifying and working with recurring patterns.',
 'Noticing stress spikes on Wednesdays. Recognizing emotional triggers.',
 FALSE, FALSE, 'May surface uncomfortable insights', 3),

('structural', 'Structural/Schema', 
 'Working with underlying beliefs, assumptions, mental models.',
 'Challenging belief that rest is laziness. Reframing failure.',
 FALSE, TRUE, 'Can be destabilizing. User consent required.', 4),

('identity', 'Identity/Self-Concept', 
 'Working with core sense of self, roles, values.',
 'Who am I beyond my job? What do I actually value?',
 FALSE, TRUE, 'Significant work. Consent + opt-out always available.', 5),

('foundational', 'Foundational/Transformational', 
 'Existential exploration. Deep restructuring of worldview.',
 'Meaning-making after loss. Fundamental life transitions.',
 TRUE, TRUE, 'Professional guidance recommended. Buddy/support system advised.', 6);


-- -----------------------------------------------------------------------------
-- SOURCE DIMENSION (Individual ↔ Collective)
-- -----------------------------------------------------------------------------
-- Where AI draws insights from:
-- INDIVIDUAL: Only users own data and patterns
-- SIMILAR: Users with similar profiles (anonymized)
-- AGGREGATE: Population-level patterns
-- COLLECTIVE: Cross-user insights, collective wisdom

CREATE TABLE IF NOT EXISTS "ai_source_levels" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_slug" TEXT UNIQUE NOT NULL,
  "source_name" TEXT NOT NULL,
  "description" TEXT,
  "privacy_level" TEXT,  -- What data is accessed
  "anonymization_required" BOOLEAN DEFAULT TRUE,
  "requires_consent" BOOLEAN DEFAULT FALSE,
  "sort_order" INTEGER
);

INSERT INTO "ai_source_levels" ("source_slug", "source_name", "description", "privacy_level", "anonymization_required", "requires_consent", "sort_order")
VALUES
('individual', 'Individual Only', 
 'AI only uses this users own data. Complete privacy.',
 'Users own check-ins, journal, preferences only',
 FALSE, FALSE, 1),

('similar', 'Similar Profiles', 
 'AI learns from users with similar patterns (anonymized).',
 'Aggregate patterns from similar demographic/profile',
 TRUE, TRUE, 2),

('aggregate', 'Population Aggregate', 
 'AI uses population-level insights. What works for most people.',
 'Statistical patterns across all users',
 TRUE, FALSE, 3),

('collective', 'Collective Wisdom', 
 'AI synthesizes insights across user base for novel suggestions.',
 'Cross-user pattern recognition, emerging insights',
 TRUE, TRUE, 4),

('research', 'Research Pool', 
 'User contributes (anonymized) data to improve the system.',
 'Opted-in data contribution for system learning',
 TRUE, TRUE, 5);


-- -----------------------------------------------------------------------------
-- CONFIDENCE DIMENSION (Established ↔ Experimental)
-- -----------------------------------------------------------------------------
-- How established is the approach:
-- GOLD_STANDARD: Multiple meta-analyses, clinical guidelines
-- ESTABLISHED: Good evidence, widely practiced
-- EMERGING: Promising but limited evidence
-- TRADITIONAL: Lineage-based, not RCT-validated
-- EXPERIMENTAL: Novel combinations, beta testing
-- FRONTIER: Beyond current practice, user-generated

CREATE TABLE IF NOT EXISTS "ai_confidence_levels" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "confidence_slug" TEXT UNIQUE NOT NULL,
  "confidence_name" TEXT NOT NULL,
  "description" TEXT,
  "evidence_basis" TEXT,
  "disclaimer_required" BOOLEAN DEFAULT FALSE,
  "disclaimer_text" TEXT,
  "sort_order" INTEGER
);

INSERT INTO "ai_confidence_levels" ("confidence_slug", "confidence_name", "description", "evidence_basis", "disclaimer_required", "disclaimer_text", "sort_order")
VALUES
('gold_standard', 'Gold Standard', 
 'Highest evidence tier. Multiple meta-analyses, clinical guidelines.',
 'Cochrane reviews, clinical guidelines, extensive RCT evidence',
 FALSE, NULL, 1),

('established', 'Established Practice', 
 'Good evidence base. Widely practiced by professionals.',
 'Multiple RCTs, professional consensus, decades of practice',
 FALSE, NULL, 2),

('emerging', 'Emerging Evidence', 
 'Promising but limited. Early research, growing interest.',
 'Early RCTs, mechanistic studies, pilot data',
 FALSE, NULL, 3),

('traditional', 'Traditional/Lineage', 
 'Based on traditional practice, not RCT-validated. Centuries of use.',
 'Traditional lineage, historical practice, anecdotal',
 TRUE, 'This approach is based on traditional practice rather than randomized controlled trials.', 4),

('experimental', 'Experimental/Beta', 
 'Novel combinations or approaches. Being tested.',
 'Theoretical basis, limited testing, user feedback',
 TRUE, 'This is an experimental approach. Please monitor your response and discontinue if uncomfortable.', 5),

('frontier', 'Frontier/User-Generated', 
 'Beyond established practice. May include user-created blends.',
 'User-generated, AI-synthesized, novel territory',
 TRUE, 'This approach goes beyond established practice. It is experimental. You are helping pioneer new territory.', 6);


-- -----------------------------------------------------------------------------
-- CROSS-DOMAIN MAPPINGS (How techniques transfer)
-- -----------------------------------------------------------------------------
-- When AI widens scope, how do techniques translate?

CREATE TABLE IF NOT EXISTS "cross_domain_mappings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_domain" TEXT NOT NULL,  -- e.g., "athletic_recovery"
  "target_domain" TEXT NOT NULL,  -- e.g., "anxiety_management"
  "technique_pattern" TEXT,  -- What aspect transfers
  "translation_notes" TEXT,  -- How to adapt
  "confidence" TEXT,  -- How reliable is this mapping
  "evidence_sources" TEXT,  -- What supports this transfer
  "contraindications" TEXT,  -- When NOT to transfer
  "is_verified" BOOLEAN DEFAULT FALSE,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

-- Example cross-domain mappings
INSERT INTO "cross_domain_mappings" 
("source_domain", "target_domain", "technique_pattern", "translation_notes", "confidence")
VALUES
('athletic_breathing', 'anxiety_management',
 'Controlled exhalation for parasympathetic activation',
 'Athletic CO2 tolerance training translates well to anxiety. Reduce intensity, emphasize safety.',
 'emerging'),

('meditation_attention', 'chronic_pain',
 'Non-reactive awareness of sensation',
 'Mindfulness attention training applies to pain. Avoid forcing, emphasize acceptance.',
 'established'),

('addiction_recovery', 'grief_processing',
 'Sitting with difficult affect without acting out',
 'Distress tolerance skills transfer. Different content, same container.',
 'emerging'),

('athletic_periodization', 'burnout_recovery',
 'Structured rest and progressive loading',
 'Recovery cycles from sports apply to work burnout. Deload phases, active recovery.',
 'emerging'),

('trauma_somatic', 'performance_anxiety',
 'Nervous system regulation through body awareness',
 'Somatic tools for trauma apply to performance. Different trigger, same physiology.',
 'established'),

('contemplative_surrender', 'control_issues',
 'Practice of non-doing, allowing',
 'Spiritual surrender practices can help control patterns. Reframe as strength not weakness.',
 'traditional');


-- -----------------------------------------------------------------------------
-- USER TECHNIQUE BLENDS (User-created combinations)
-- -----------------------------------------------------------------------------
-- Users can create their own techniques by blending existing ones

CREATE TABLE IF NOT EXISTS "user_technique_blends" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "blend_name" TEXT NOT NULL,
  "description" TEXT,
  
  -- Component techniques
  "base_technique_ids" TEXT,  -- Comma-separated technique IDs
  "modifications" JSONB,  -- What they changed
  
  -- Personal targets
  "user_objectives" TEXT,  -- What theyre trying to achieve
  "personal_cues" TEXT,  -- Their own language/cues
  
  -- Tracking
  "times_used" INTEGER DEFAULT 0,
  "effectiveness_rating" INTEGER,  -- Self-rated 1-10
  "notes" TEXT,
  
  -- Sharing
  "is_private" BOOLEAN DEFAULT TRUE,
  "share_anonymously" BOOLEAN DEFAULT FALSE,  -- Contribute to collective
  
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);


-- -----------------------------------------------------------------------------
-- SESSION SCOPE LOG (AI decision transparency)
-- -----------------------------------------------------------------------------
-- Logs AI decisions about scope, depth, source for full transparency

CREATE TABLE IF NOT EXISTS "session_scope_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "timestamp" TIMESTAMPTZ DEFAULT NOW(),
  
  -- AI selections
  "scope_used" TEXT,  -- narrow, medium, wide, etc.
  "depth_used" TEXT,  -- surface, pattern, structural, etc.
  "source_used" TEXT,  -- individual, aggregate, collective
  "confidence_used" TEXT,  -- established, experimental, frontier
  
  -- Reasoning
  "scope_reasoning" TEXT,
  "depth_reasoning" TEXT,
  "why_this_combination" TEXT,
  
  -- User context that informed decisions
  "user_state_snapshot" JSONB,  -- Mood, energy, receptivity at time
  "resistance_detected" TEXT,  -- What resistance patterns were noted
  "alternative_paths_considered" TEXT,  -- What else AI considered
  
  -- Flags
  "experimental_flag" BOOLEAN DEFAULT FALSE,
  "disclaimer_shown" BOOLEAN DEFAULT FALSE,
  "user_consent_obtained" BOOLEAN DEFAULT FALSE
);


-- -----------------------------------------------------------------------------
-- AGGREGATE PATTERNS (Collective wisdom - anonymized)
-- -----------------------------------------------------------------------------
-- Population-level insights the AI can draw from

CREATE TABLE IF NOT EXISTS "aggregate_patterns" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pattern_slug" TEXT UNIQUE NOT NULL,
  "pattern_name" TEXT NOT NULL,
  "description" TEXT,
  
  -- What the pattern is
  "condition_cluster" TEXT,  -- What user states this applies to
  "effective_interventions" TEXT,  -- What works
  "ineffective_interventions" TEXT,  -- What doesnt work
  
  -- Statistics
  "sample_size" INTEGER,
  "confidence_interval" TEXT,
  "last_updated" TIMESTAMPTZ DEFAULT NOW(),
  
  -- Source
  "derived_from" TEXT,  -- 'user_data', 'research', 'hybrid'
  "is_verified" BOOLEAN DEFAULT FALSE
);

-- Example aggregate patterns
INSERT INTO "aggregate_patterns" 
("pattern_slug", "pattern_name", "description", "condition_cluster", "effective_interventions", "sample_size")
VALUES
('therapy_resistant_anxiety', 'Therapy-Resistant Anxiety Pattern',
 'Users who have tried therapy and remain skeptical of clinical approaches.',
 'anxiety + therapy_history + resistance_to_clinical',
 'somatic_approaches, contemplative_practices, peer_support, gradual_exposure_self_directed',
 150),

('high_achiever_burnout', 'High Achiever Burnout Pattern',
 'Successful users who push too hard and resist rest.',
 'burnout + high_achievement + resistance_to_rest',
 'periodization_framing, permission_practices, identity_work, redefining_success',
 200),

('sleep_anxiety_loop', 'Sleep Anxiety Loop',
 'Users whose sleep anxiety creates more sleep problems.',
 'insomnia + sleep_anxiety + trying_too_hard',
 'paradoxical_intention, nsdr, removing_sleep_pressure, acceptance_approaches',
 180);


-- -----------------------------------------------------------------------------
-- DEEP WORK PERMISSIONS (Consent for restructuring)
-- -----------------------------------------------------------------------------
-- Explicit consent for AI to work at deeper levels

CREATE TABLE IF NOT EXISTS "deep_work_permissions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  
  -- What theyre consenting to
  "pattern_work_enabled" BOOLEAN DEFAULT FALSE,
  "structural_work_enabled" BOOLEAN DEFAULT FALSE,
  "identity_work_enabled" BOOLEAN DEFAULT FALSE,
  "foundational_work_enabled" BOOLEAN DEFAULT FALSE,
  
  -- Scope permissions
  "wide_scope_enabled" BOOLEAN DEFAULT FALSE,
  "universal_scope_enabled" BOOLEAN DEFAULT FALSE,
  "experimental_enabled" BOOLEAN DEFAULT FALSE,
  
  -- Collective permissions
  "aggregate_insights_enabled" BOOLEAN DEFAULT TRUE,
  "collective_wisdom_enabled" BOOLEAN DEFAULT FALSE,
  "contribute_to_research" BOOLEAN DEFAULT FALSE,
  
  -- Safety rails
  "professional_support_confirmed" BOOLEAN DEFAULT FALSE,
  "buddy_system_enabled" BOOLEAN DEFAULT FALSE,
  "emergency_contact_set" BOOLEAN DEFAULT FALSE,
  
  -- Consent tracking
  "consent_given_at" TIMESTAMPTZ,
  "consent_reviewed_at" TIMESTAMPTZ,
  "consent_version" TEXT,
  
  UNIQUE("user_id")
);


-- -----------------------------------------------------------------------------
-- EXPERIMENTAL FLAGS (Beta features, novel approaches)
-- -----------------------------------------------------------------------------
-- Tags content/approaches as experimental with appropriate warnings

CREATE TABLE IF NOT EXISTS "experimental_flags" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content_type" TEXT NOT NULL,  -- 'technique', 'combination', 'approach'
  "content_id" TEXT NOT NULL,
  "flag_type" TEXT NOT NULL,  -- 'beta', 'experimental', 'frontier', 'user_generated'
  
  -- Status
  "testing_phase" TEXT,  -- 'alpha', 'beta', 'limited_release'
  "user_count" INTEGER DEFAULT 0,
  "positive_reports" INTEGER DEFAULT 0,
  "negative_reports" INTEGER DEFAULT 0,
  "neutral_reports" INTEGER DEFAULT 0,
  
  -- Warnings
  "disclaimer_text" TEXT NOT NULL,
  "contraindication_warning" TEXT,
  "professional_consult_recommended" BOOLEAN DEFAULT FALSE,
  
  -- Lifecycle
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "promoted_to_established_at" TIMESTAMPTZ,
  "deprecated_at" TIMESTAMPTZ,
  "deprecation_reason" TEXT,
  
  UNIQUE("content_type", "content_id")
);


-- -----------------------------------------------------------------------------
-- AI REASONING TRANSPARENCY
-- -----------------------------------------------------------------------------
-- Users can always ask "why did you suggest this?"

CREATE TABLE IF NOT EXISTS "ai_decision_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "session_id" TEXT,
  "timestamp" TIMESTAMPTZ DEFAULT NOW(),
  
  -- What was decided
  "decision_type" TEXT,  -- 'technique_selection', 'scope_change', 'depth_shift'
  "decision_made" TEXT,
  
  -- Full reasoning chain
  "user_context_considered" JSONB,
  "options_evaluated" JSONB,
  "selection_criteria" TEXT,
  "final_reasoning" TEXT,
  
  -- Alternatives
  "alternatives_available" JSONB,
  "why_not_alternatives" TEXT,
  
  -- Transparency
  "user_can_query" BOOLEAN DEFAULT TRUE,
  "explanation_given" BOOLEAN DEFAULT FALSE
);


-- -----------------------------------------------------------------------------
-- META-LENS PRESETS (Common configurations)
-- -----------------------------------------------------------------------------
-- Pre-configured combinations of scope/depth/source/confidence

CREATE TABLE IF NOT EXISTS "meta_lens_presets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "preset_slug" TEXT UNIQUE NOT NULL,
  "preset_name" TEXT NOT NULL,
  "description" TEXT,
  
  -- Configuration
  "default_scope" TEXT,
  "default_depth" TEXT,
  "default_source" TEXT,
  "default_confidence" TEXT,
  
  -- Lens + Persona defaults
  "preferred_lenses" TEXT,  -- Comma-separated
  "preferred_personas" TEXT,
  "preferred_knowledge_bases" TEXT,
  
  -- Use case
  "best_for" TEXT,
  "not_for" TEXT,
  
  "icon" TEXT,
  "sort_order" INTEGER
);

INSERT INTO "meta_lens_presets" 
("preset_slug", "preset_name", "description", "default_scope", "default_depth", "default_source", "default_confidence", "preferred_lenses", "preferred_personas", "best_for", "icon", "sort_order")
VALUES
('safe_start', 'Safe Start',
 'Conservative defaults. Evidence-based, surface-level, individual focus.',
 'narrow', 'surface', 'individual', 'established',
 'western,plain', 'Friendly Neighbor,Clinical Therapist',
 'New users, cautious users, unknown history',
 '🛡️', 1),

('exploratory', 'Open Explorer',
 'Wider scope, willing to try adjacent domains.',
 'medium', 'pattern', 'aggregate', 'emerging',
 'hybrid,somatic', 'Somatic Guide,Alan Watts-like',
 'Curious users, some experience, open to new',
 '🔭', 2),

('deep_diver', 'Deep Diver',
 'Narrow but deep. Specialist focus, structural work.',
 'focused', 'structural', 'individual', 'established',
 'somatic,contemplative', 'Zen Teacher,Somatic Guide',
 'Experienced practitioners, ready for depth',
 '🌊', 3),

('synthesizer', 'Cross-Domain Synthesizer',
 'Wide scope, collective wisdom, experimental combinations.',
 'wide', 'pattern', 'collective', 'experimental',
 'hybrid,athletic', 'Research Scientist,Performance Coach',
 'Tried everything, looking for novel approaches',
 '🔀', 4),

('frontier_explorer', 'Frontier Explorer',
 'Maximum openness. Experimental, user-generated, collective.',
 'universal', 'identity', 'collective', 'frontier',
 'personalized,spiritual', 'Mystic Poet,Elder Guide',
 'Advanced users with professional support, consent to pioneer',
 '🚀', 5);


-- -----------------------------------------------------------------------------
-- INDEXES
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS "idx_scope_log_user" ON "session_scope_log" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_scope_log_session" ON "session_scope_log" ("session_id");
CREATE INDEX IF NOT EXISTS "idx_blend_user" ON "user_technique_blends" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_permissions_user" ON "deep_work_permissions" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_decision_log_user" ON "ai_decision_log" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_aggregate_patterns_cluster" ON "aggregate_patterns" ("condition_cluster");


