-- =============================================================================
-- META-INTELLIGENCE LAYER - Safe Version (handles existing data)
-- =============================================================================
-- Uses ON CONFLICT DO NOTHING to skip existing rows
-- =============================================================================

-- SCOPE DIMENSION
CREATE TABLE IF NOT EXISTS "ai_scope_levels" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "scope_slug" TEXT UNIQUE NOT NULL,
  "scope_name" TEXT NOT NULL,
  "description" TEXT,
  "example_use" TEXT,
  "risk_level" TEXT,
  "requires_consent" BOOLEAN DEFAULT FALSE,
  "sort_order" INTEGER
);

INSERT INTO "ai_scope_levels" ("scope_slug", "scope_name", "description", "example_use", "risk_level", "requires_consent", "sort_order")
VALUES
('narrow', 'Narrow/Specialist', 'AI stays within a single domain.', 'User wants only TCM-based approaches.', 'low', FALSE, 1),
('focused', 'Focused/Related', 'AI draws from closely related domains.', 'User doing breathwork, AI suggests body awareness.', 'low', FALSE, 2),
('medium', 'Medium/Adjacent', 'AI draws from adjacent fields.', 'User stressed, AI suggests sports recovery.', 'low', FALSE, 3),
('wide', 'Wide/Cross-Domain', 'AI synthesizes across different domains.', 'User resistant to therapy, AI uses contemplative.', 'medium', FALSE, 4),
('universal', 'Universal/Synthesis', 'AI can draw from any field.', 'User has tried everything, AI explores.', 'high', TRUE, 5),
('experimental', 'Experimental/Frontier', 'AI explores beyond established practice.', 'User consents to trying something new.', 'high', TRUE, 6)
ON CONFLICT (scope_slug) DO NOTHING;

-- DEPTH DIMENSION
CREATE TABLE IF NOT EXISTS "ai_depth_levels" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "depth_slug" TEXT UNIQUE NOT NULL,
  "depth_name" TEXT NOT NULL,
  "description" TEXT,
  "example_work" TEXT,
  "requires_professional" BOOLEAN DEFAULT FALSE,
  "requires_consent" BOOLEAN DEFAULT FALSE,
  "safety_notes" TEXT,
  "sort_order" INTEGER
);

INSERT INTO "ai_depth_levels" ("depth_slug", "depth_name", "description", "example_work", "requires_professional", "requires_consent", "safety_notes", "sort_order")
VALUES
('surface', 'Surface/Behavioral', 'Immediate, practical interventions.', 'Breathing exercise for acute stress.', FALSE, FALSE, 'Safe for all users', 1),
('habit', 'Habit/Practice', 'Building consistent practices.', 'Establishing morning routine.', FALSE, FALSE, 'Safe for all users', 2),
('pattern', 'Pattern/Recurring', 'Identifying recurring patterns.', 'Noticing stress spikes.', FALSE, FALSE, 'May surface insights', 3),
('structural', 'Structural/Schema', 'Working with underlying beliefs.', 'Challenging belief that rest is laziness.', FALSE, TRUE, 'Consent required', 4),
('identity', 'Identity/Self-Concept', 'Working with core sense of self.', 'Who am I beyond my job?', FALSE, TRUE, 'Significant work', 5),
('foundational', 'Foundational/Transformational', 'Existential exploration.', 'Meaning-making after loss.', TRUE, TRUE, 'Professional recommended', 6)
ON CONFLICT (depth_slug) DO NOTHING;

-- SOURCE DIMENSION
CREATE TABLE IF NOT EXISTS "ai_source_levels" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_slug" TEXT UNIQUE NOT NULL,
  "source_name" TEXT NOT NULL,
  "description" TEXT,
  "privacy_level" TEXT,
  "anonymization_required" BOOLEAN DEFAULT TRUE,
  "requires_consent" BOOLEAN DEFAULT FALSE,
  "sort_order" INTEGER
);

INSERT INTO "ai_source_levels" ("source_slug", "source_name", "description", "privacy_level", "anonymization_required", "requires_consent", "sort_order")
VALUES
('individual', 'Individual Only', 'AI only uses this users own data.', 'Users own data only', FALSE, FALSE, 1),
('similar', 'Similar Profiles', 'AI learns from similar users (anonymized).', 'Aggregate from similar', TRUE, TRUE, 2),
('aggregate', 'Population Aggregate', 'AI uses population-level insights.', 'Statistical patterns', TRUE, FALSE, 3),
('collective', 'Collective Wisdom', 'AI synthesizes insights across user base.', 'Cross-user patterns', TRUE, TRUE, 4),
('research', 'Research Pool', 'User contributes data to improve system.', 'Opted-in contribution', TRUE, TRUE, 5)
ON CONFLICT (source_slug) DO NOTHING;

-- CONFIDENCE DIMENSION
CREATE TABLE IF NOT EXISTS "ai_confidence_levels" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "confidence_slug" TEXT UNIQUE NOT NULL,
  "confidence_name" TEXT NOT NULL,
  "description" TEXT,
  "evidence_basis" TEXT,
  "disclaimer_required" BOOLEAN DEFAULT FALSE,
  "disclaimer_text" TEXT,
  "sort_order" INTEGER
);

INSERT INTO "ai_confidence_levels" ("confidence_slug", "confidence_name", "description", "evidence_basis", "disclaimer_required", "disclaimer_text", "sort_order")
VALUES
('gold_standard', 'Gold Standard', 'Highest evidence tier.', 'Cochrane reviews, clinical guidelines', FALSE, NULL, 1),
('established', 'Established Practice', 'Good evidence base.', 'Multiple RCTs, professional consensus', FALSE, NULL, 2),
('emerging', 'Emerging Evidence', 'Promising but limited.', 'Early RCTs, pilot data', FALSE, NULL, 3),
('traditional', 'Traditional/Lineage', 'Based on traditional practice.', 'Traditional lineage, centuries of use', TRUE, 'Based on traditional practice.', 4),
('experimental', 'Experimental/Beta', 'Novel combinations.', 'Theoretical basis, limited testing', TRUE, 'Experimental approach. Monitor response.', 5),
('frontier', 'Frontier/User-Generated', 'Beyond established practice.', 'User-generated, AI-synthesized', TRUE, 'Beyond established practice. Pioneering territory.', 6)
ON CONFLICT (confidence_slug) DO NOTHING;

-- CROSS-DOMAIN MAPPINGS
CREATE TABLE IF NOT EXISTS "cross_domain_mappings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_domain" TEXT NOT NULL,
  "target_domain" TEXT NOT NULL,
  "technique_pattern" TEXT,
  "translation_notes" TEXT,
  "confidence" TEXT,
  "evidence_sources" TEXT,
  "contraindications" TEXT,
  "is_verified" BOOLEAN DEFAULT FALSE,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO "cross_domain_mappings" ("source_domain", "target_domain", "technique_pattern", "translation_notes", "confidence")
SELECT * FROM (VALUES
('athletic_breathing', 'anxiety_management', 'Controlled exhalation', 'Athletic CO2 tolerance for anxiety.', 'emerging'),
('meditation_attention', 'chronic_pain', 'Non-reactive awareness', 'Mindfulness applies to pain.', 'established'),
('addiction_recovery', 'grief_processing', 'Sitting with difficult affect', 'Distress tolerance transfers.', 'emerging'),
('athletic_periodization', 'burnout_recovery', 'Structured rest', 'Recovery cycles for burnout.', 'emerging'),
('trauma_somatic', 'performance_anxiety', 'Nervous system regulation', 'Somatic tools for performance.', 'established'),
('contemplative_surrender', 'control_issues', 'Practice of non-doing', 'Surrender for control patterns.', 'traditional')
) AS v(source_domain, target_domain, technique_pattern, translation_notes, confidence)
WHERE NOT EXISTS (
  SELECT 1 FROM cross_domain_mappings WHERE source_domain = v.source_domain AND target_domain = v.target_domain
);

-- USER TECHNIQUE BLENDS
CREATE TABLE IF NOT EXISTS "user_technique_blends" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "blend_name" TEXT NOT NULL,
  "description" TEXT,
  "base_technique_ids" TEXT,
  "modifications" JSONB,
  "user_objectives" TEXT,
  "personal_cues" TEXT,
  "times_used" INTEGER DEFAULT 0,
  "effectiveness_rating" INTEGER,
  "notes" TEXT,
  "is_private" BOOLEAN DEFAULT TRUE,
  "share_anonymously" BOOLEAN DEFAULT FALSE,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

-- SESSION SCOPE LOG
CREATE TABLE IF NOT EXISTS "session_scope_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "timestamp" TIMESTAMPTZ DEFAULT NOW(),
  "scope_used" TEXT,
  "depth_used" TEXT,
  "source_used" TEXT,
  "confidence_used" TEXT,
  "scope_reasoning" TEXT,
  "depth_reasoning" TEXT,
  "why_this_combination" TEXT,
  "user_state_snapshot" JSONB,
  "resistance_detected" TEXT,
  "alternative_paths_considered" TEXT,
  "experimental_flag" BOOLEAN DEFAULT FALSE,
  "disclaimer_shown" BOOLEAN DEFAULT FALSE,
  "user_consent_obtained" BOOLEAN DEFAULT FALSE
);

-- AGGREGATE PATTERNS
CREATE TABLE IF NOT EXISTS "aggregate_patterns" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pattern_slug" TEXT UNIQUE NOT NULL,
  "pattern_name" TEXT NOT NULL,
  "description" TEXT,
  "condition_cluster" TEXT,
  "effective_interventions" TEXT,
  "ineffective_interventions" TEXT,
  "sample_size" INTEGER,
  "confidence_interval" TEXT,
  "last_updated" TIMESTAMPTZ DEFAULT NOW(),
  "derived_from" TEXT,
  "is_verified" BOOLEAN DEFAULT FALSE
);

INSERT INTO "aggregate_patterns" ("pattern_slug", "pattern_name", "description", "condition_cluster", "effective_interventions", "sample_size")
VALUES
('therapy_resistant_anxiety', 'Therapy-Resistant Anxiety', 'Users who tried therapy and remain skeptical.', 'anxiety + therapy_history + resistance', 'somatic_approaches, contemplative_practices', 150),
('high_achiever_burnout', 'High Achiever Burnout', 'Successful users who push too hard.', 'burnout + high_achievement + resistance_to_rest', 'periodization_framing, permission_practices', 200),
('sleep_anxiety_loop', 'Sleep Anxiety Loop', 'Users whose sleep anxiety creates more problems.', 'insomnia + sleep_anxiety + trying_too_hard', 'paradoxical_intention, nsdr, acceptance', 180)
ON CONFLICT (pattern_slug) DO NOTHING;

-- DEEP WORK PERMISSIONS
CREATE TABLE IF NOT EXISTS "deep_work_permissions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" TEXT NOT NULL UNIQUE,
  "pattern_work_enabled" BOOLEAN DEFAULT FALSE,
  "structural_work_enabled" BOOLEAN DEFAULT FALSE,
  "identity_work_enabled" BOOLEAN DEFAULT FALSE,
  "foundational_work_enabled" BOOLEAN DEFAULT FALSE,
  "wide_scope_enabled" BOOLEAN DEFAULT FALSE,
  "universal_scope_enabled" BOOLEAN DEFAULT FALSE,
  "experimental_enabled" BOOLEAN DEFAULT FALSE,
  "aggregate_insights_enabled" BOOLEAN DEFAULT TRUE,
  "collective_wisdom_enabled" BOOLEAN DEFAULT FALSE,
  "contribute_to_research" BOOLEAN DEFAULT FALSE,
  "professional_support_confirmed" BOOLEAN DEFAULT FALSE,
  "buddy_system_enabled" BOOLEAN DEFAULT FALSE,
  "emergency_contact_set" BOOLEAN DEFAULT FALSE,
  "consent_given_at" TIMESTAMPTZ,
  "consent_reviewed_at" TIMESTAMPTZ,
  "consent_version" TEXT
);

-- EXPERIMENTAL FLAGS
CREATE TABLE IF NOT EXISTS "experimental_flags" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content_type" TEXT NOT NULL,
  "content_id" TEXT NOT NULL,
  "flag_type" TEXT NOT NULL,
  "testing_phase" TEXT,
  "user_count" INTEGER DEFAULT 0,
  "positive_reports" INTEGER DEFAULT 0,
  "negative_reports" INTEGER DEFAULT 0,
  "neutral_reports" INTEGER DEFAULT 0,
  "disclaimer_text" TEXT NOT NULL,
  "contraindication_warning" TEXT,
  "professional_consult_recommended" BOOLEAN DEFAULT FALSE,
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "promoted_to_established_at" TIMESTAMPTZ,
  "deprecated_at" TIMESTAMPTZ,
  "deprecation_reason" TEXT,
  UNIQUE("content_type", "content_id")
);

-- AI DECISION LOG
CREATE TABLE IF NOT EXISTS "ai_decision_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "session_id" TEXT,
  "timestamp" TIMESTAMPTZ DEFAULT NOW(),
  "decision_type" TEXT,
  "decision_made" TEXT,
  "user_context_considered" JSONB,
  "options_evaluated" JSONB,
  "selection_criteria" TEXT,
  "final_reasoning" TEXT,
  "alternatives_available" JSONB,
  "why_not_alternatives" TEXT,
  "user_can_query" BOOLEAN DEFAULT TRUE,
  "explanation_given" BOOLEAN DEFAULT FALSE
);

-- META-LENS PRESETS
CREATE TABLE IF NOT EXISTS "meta_lens_presets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "preset_slug" TEXT UNIQUE NOT NULL,
  "preset_name" TEXT NOT NULL,
  "description" TEXT,
  "default_scope" TEXT,
  "default_depth" TEXT,
  "default_source" TEXT,
  "default_confidence" TEXT,
  "preferred_lenses" TEXT,
  "preferred_personas" TEXT,
  "preferred_knowledge_bases" TEXT,
  "best_for" TEXT,
  "not_for" TEXT,
  "icon" TEXT,
  "sort_order" INTEGER
);

INSERT INTO "meta_lens_presets" ("preset_slug", "preset_name", "description", "default_scope", "default_depth", "default_source", "default_confidence", "preferred_lenses", "preferred_personas", "best_for", "icon", "sort_order")
VALUES
('safe_start', 'Safe Start', 'Conservative defaults.', 'narrow', 'surface', 'individual', 'established', 'western,plain', 'Friendly Neighbor', 'New users', '🛡️', 1),
('exploratory', 'Open Explorer', 'Wider scope, willing to try.', 'medium', 'pattern', 'aggregate', 'emerging', 'hybrid,somatic', 'Alan Watts-like', 'Curious users', '🔭', 2),
('deep_diver', 'Deep Diver', 'Narrow but deep.', 'focused', 'structural', 'individual', 'established', 'somatic,contemplative', 'Zen Teacher', 'Practitioners', '🌊', 3),
('synthesizer', 'Cross-Domain Synthesizer', 'Wide scope, collective.', 'wide', 'pattern', 'collective', 'experimental', 'hybrid,athletic', 'Research Scientist', 'Tried everything', '🔀', 4),
('frontier_explorer', 'Frontier Explorer', 'Maximum openness.', 'universal', 'identity', 'collective', 'frontier', 'personalized,spiritual', 'Mystic Poet', 'Advanced + support', '🚀', 5)
ON CONFLICT (preset_slug) DO NOTHING;

-- INDEXES
CREATE INDEX IF NOT EXISTS "idx_scope_log_user" ON "session_scope_log" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_scope_log_session" ON "session_scope_log" ("session_id");
CREATE INDEX IF NOT EXISTS "idx_blend_user" ON "user_technique_blends" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_permissions_user" ON "deep_work_permissions" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_decision_log_user" ON "ai_decision_log" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_aggregate_patterns_cluster" ON "aggregate_patterns" ("condition_cluster");

-- Success message
SELECT 'Meta-Intelligence Layer created. ' ||
       (SELECT COUNT(*) FROM ai_scope_levels) || ' scope levels, ' ||
       (SELECT COUNT(*) FROM ai_depth_levels) || ' depth levels, ' ||
       (SELECT COUNT(*) FROM meta_lens_presets) || ' meta-presets.' AS status;


