-- =============================================================================
-- PERSONAS + KNOWLEDGE BASES - Safe Version (handles existing data)
-- =============================================================================
-- Uses ON CONFLICT DO NOTHING to skip existing rows
-- =============================================================================

-- Create knowledge_bases table if not exists
CREATE TABLE IF NOT EXISTS "knowledge_bases" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kb_slug" TEXT UNIQUE NOT NULL,
  "kb_name" TEXT NOT NULL,
  "kb_description" TEXT,
  "kb_type" TEXT,
  "paradigm_family" TEXT,
  "cultural_origin" TEXT,
  "era" TEXT,
  "is_system" BOOLEAN DEFAULT TRUE,
  "is_public" BOOLEAN DEFAULT TRUE,
  "requires_training" BOOLEAN DEFAULT FALSE,
  "maturity_gate" TEXT,
  "primary_topics" TEXT,
  "language_register" TEXT,
  "evidence_level" TEXT,
  "contraindication_tags" TEXT,
  "requires_disclaimer" BOOLEAN DEFAULT FALSE,
  "disclaimer_text" TEXT,
  "icon" TEXT,
  "sort_order" INTEGER DEFAULT 100,
  "is_active" BOOLEAN DEFAULT TRUE,
  "notes" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "user_knowledge_access" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "kb_id" BIGINT REFERENCES "knowledge_bases"("id"),
  "access_level" TEXT DEFAULT 'read',
  "granted_at" TIMESTAMPTZ DEFAULT NOW(),
  "granted_by" TEXT,
  "notes" TEXT,
  UNIQUE("user_id", "kb_id")
);

CREATE TABLE IF NOT EXISTS "programme_knowledge_map" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "programme_profile_id" TEXT NOT NULL,
  "kb_id" BIGINT REFERENCES "knowledge_bases"("id"),
  "is_required" BOOLEAN DEFAULT FALSE,
  "is_default" BOOLEAN DEFAULT TRUE,
  "weight" INTEGER DEFAULT 50,
  UNIQUE("programme_profile_id", "kb_id")
);

CREATE TABLE IF NOT EXISTS "persona_lens_compatibility" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona_id" BIGINT,
  "lens_id" BIGINT,
  "compatibility_score" INTEGER DEFAULT 50,
  "notes" TEXT
);

CREATE TABLE IF NOT EXISTS "persona_kb_compatibility" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona_id" BIGINT,
  "kb_id" BIGINT,
  "compatibility_score" INTEGER DEFAULT 50,
  "notes" TEXT
);

-- Insert knowledge bases with ON CONFLICT DO NOTHING
INSERT INTO "knowledge_bases" (
  "kb_slug", "kb_name", "kb_description", "kb_type", "paradigm_family",
  "cultural_origin", "era", "primary_topics", "language_register",
  "evidence_level", "maturity_gate", "icon", "sort_order"
) VALUES 
('yoga_sutras', 'Yoga Sutras of Patanjali', 
 'Classical 8-limbed yoga philosophy.',
 'traditional_text', 'eastern', 'Indian', 'classical',
 'meditation, ethics, consciousness', 'poetic', 'traditional', 'intermediate', '📿', 10),
('bhagavad_gita', 'Bhagavad Gita', 
 'Hindu philosophical text on dharma, action, and devotion.',
 'traditional_text', 'eastern', 'Indian', 'ancient',
 'action, devotion, knowledge', 'poetic', 'traditional', 'intermediate', '📜', 11),
('tao_te_ching', 'Tao Te Ching', 
 'Foundational Taoist text. Wu-wei, naturalness.',
 'traditional_text', 'eastern', 'Chinese', 'ancient',
 'naturalness, non-doing, flow', 'poetic', 'traditional', 'beginner', '☯️', 12),
('huangdi_neijing', 'Huangdi Neijing', 
 'Foundational TCM text. Qi, meridians, organ theory.',
 'traditional_text', 'eastern', 'Chinese', 'ancient',
 'medicine, qi, meridians', 'technical', 'traditional', 'intermediate', '📕', 13),
('ayurveda_classics', 'Ayurvedic Classics', 
 'Classical Ayurvedic medical texts.',
 'traditional_text', 'eastern', 'Indian', 'classical',
 'constitution, diet, lifestyle', 'technical', 'traditional', 'intermediate', '🕉️', 14),
('zen_koans', 'Zen Koan Collections', 
 'Paradoxical teaching stories from Zen tradition.',
 'traditional_text', 'eastern', 'Japanese/Chinese', 'classical',
 'awakening, paradox', 'poetic', 'traditional', 'advanced', '🔔', 15),
('sufi_poetry', 'Sufi Poetry', 
 'Mystical Islamic poetry. Divine love, union.',
 'traditional_text', 'eastern', 'Persian', 'classical',
 'love, heart, union', 'poetic', 'traditional', 'beginner', '🌹', 16),
('pubmed_neuroscience', 'PubMed Neuroscience', 
 'Peer-reviewed neuroscience research.',
 'research', 'scientific', 'Western', 'contemporary',
 'neuroscience, physiology', 'academic', 'peer_reviewed', 'none', '🧠', 20),
('pubmed_psychology', 'PubMed Psychology', 
 'Peer-reviewed psychology research.',
 'research', 'scientific', 'Western', 'contemporary',
 'psychology, mental health', 'academic', 'peer_reviewed', 'none', '🔬', 21),
('cochrane_reviews', 'Cochrane Reviews', 
 'Systematic reviews and meta-analyses.',
 'research', 'scientific', 'Western', 'contemporary',
 'evidence synthesis', 'academic', 'peer_reviewed', 'none', '📊', 22),
('sports_science', 'Sports Science Research', 
 'Performance, recovery, periodization.',
 'research', 'scientific', 'Western', 'contemporary',
 'performance, recovery', 'academic', 'peer_reviewed', 'none', '🏃', 23),
('clinical_guidelines', 'Clinical Practice Guidelines', 
 'Evidence-based treatment guidelines.',
 'clinical_guideline', 'scientific', 'Western', 'contemporary',
 'treatment, diagnosis', 'technical', 'peer_reviewed', 'professional', '📋', 30),
('safety_contraindications', 'Safety Database', 
 'When NOT to do something. Red flags.',
 'clinical_guideline', 'scientific', 'Western', 'contemporary',
 'safety, contraindications', 'technical', 'peer_reviewed', 'none', '⚠️', 31),
('somatic_experiencing', 'Somatic Experiencing', 
 'Peter Levine, trauma and the body.',
 'lineage', 'modern', 'Western', 'modern',
 'trauma, nervous system', 'practical', 'mixed', 'intermediate', '🫀', 40),
('polyvagal_theory', 'Polyvagal Theory', 
 'Stephen Porges. Vagal states, neuroception.',
 'lineage', 'modern', 'Western', 'contemporary',
 'nervous system, safety', 'practical', 'peer_reviewed', 'beginner', '🌊', 41),
('mbsr_mbct', 'MBSR/MBCT Research', 
 'Mindfulness-Based Stress Reduction evidence.',
 'research', 'modern', 'Western', 'contemporary',
 'mindfulness, stress', 'practical', 'peer_reviewed', 'none', '🪷', 50),
('secular_meditation', 'Secular Meditation', 
 'Non-religious meditation science.',
 'research', 'modern', 'Western', 'contemporary',
 'attention, cognition', 'academic', 'peer_reviewed', 'none', '🧘', 51),
('user_journal', 'Your Personal Journal', 
 'Your own notes and reflections.',
 'user_journal', 'personal', 'User', 'contemporary',
 'personal, reflection', 'personal', 'anecdotal', 'none', '📔', 100),
('user_lineage', 'Your Teachers', 
 'Teachings from your personal teachers.',
 'lineage', 'personal', 'User', 'contemporary',
 'personal, lineage', 'personal', 'traditional', 'none', '👤', 101)
ON CONFLICT (kb_slug) DO NOTHING;

-- Insert personas (into existing archetypal_personas table)
-- Using ON CONFLICT on persona name
INSERT INTO "archetypal_personas" (
  "persona", "cognitive_style", "language_tone", "metaphor_density",
  "lineage___influence", "tradition_affinity", "nervous_system_bias",
  "primary_use_context", "safety_profile", "notes"
) VALUES 
('Clinical Therapist', 'Analytical', 'Clinical-calm', 'None',
 'CBT, DBT, evidence-based psychology', 'Western Psychology', 'Neutral',
 'Therapy-adjacent, clinical populations', 'High - trauma-aware',
 'Professional, warm but boundaried.'),
('Research Scientist', 'Analytical', 'Direct', 'None',
 'Neuroscience, physiology', 'Western Science', 'Neutral',
 'Users who want pure mechanism', 'High',
 'Explains mechanisms precisely. Cites evidence.'),
('Performance Coach', 'Directive', 'Direct', 'Low',
 'Sports psychology, elite athletics', 'Modern Performance', 'Sympathetic-leaning',
 'Athletes, high-performers', 'Medium',
 'Motivating without toxic positivity.'),
('Somatic Guide', 'Intuitive', 'Warm', 'Low',
 'Somatic Experiencing, Hakomi', 'Somatic Psychology', 'Parasympathetic',
 'Trauma recovery, embodiment', 'Very High - trauma-informed',
 'Gentle, permission-based. Always offers choice.'),
('Movement Teacher', 'Embodied', 'Warm', 'Medium',
 'Dance therapy, Feldenkrais', 'Somatic Arts', 'Mixed',
 'Movement sessions, body awareness', 'High',
 'Invites exploration, not correction.'),
('Zen Teacher', 'Minimal', 'Direct', 'Low',
 'Zen Buddhism, koans', 'Zen Buddhism', 'Parasympathetic',
 'Meditation, presence practices', 'Medium',
 'Few words, maximum impact.'),
('Mystic Poet', 'Intuitive', 'Poetic', 'Very High',
 'Rumi, Hafiz, mystical poetry', 'Sufi/Mystical', 'Parasympathetic',
 'Deep states, spiritual seekers', 'Low - may be abstract',
 'Speaks in images and metaphors.'),
('Mindfulness Teacher', 'Observational', 'Warm', 'Low',
 'MBSR, secular mindfulness', 'Secular Mindfulness', 'Parasympathetic',
 'Mainstream users, stress reduction', 'High',
 'Accessible, non-religious. Practical.'),
('TCM Practitioner', 'Diagnostic', 'Warm', 'Medium',
 'Traditional Chinese Medicine', 'Chinese Medicine', 'Mixed',
 'Users interested in TCM frameworks', 'High',
 'Uses TCM language accurately.'),
('Ayurvedic Guide', 'Constitutional', 'Warm', 'Medium',
 'Ayurveda, Dosha theory', 'Ayurveda', 'Mixed',
 'Users interested in Ayurvedic frameworks', 'High',
 'Speaks in Dosha terms.'),
('Yoga Philosopher', 'Integrative', 'Poetic', 'Medium',
 'Yoga Sutras, Tantra', 'Yogic Philosophy', 'Parasympathetic',
 'Users with yoga background', 'Medium',
 'Bridges asana and philosophy.'),
('Qigong Master', 'Embodied', 'Minimal', 'Medium',
 'Qigong, Tai Chi, Taoist cultivation', 'Taoist Arts', 'Parasympathetic',
 'Movement and breath cultivation', 'High',
 'Economy of words. Emphasis on felt experience.'),
('Friendly Neighbor', 'Simple', 'Warm', 'None',
 'Common sense, practical wisdom', 'Universal', 'Neutral',
 'New users, skeptics', 'Very High',
 'No jargon. Just practical advice.'),
('Encouraging Parent', 'Supportive', 'Warm', 'Low',
 'Attachment theory, unconditional positive regard', 'Universal', 'Parasympathetic',
 'Users needing nurturing', 'Very High - never shaming',
 'Unconditionally supportive.'),
('Elder Guide', 'Wise', 'Warm', 'Medium',
 'Life experience, generational wisdom', 'Universal', 'Parasympathetic',
 'Users seeking wisdom', 'High',
 'Speaks from experience, not theory.')
ON CONFLICT (persona) DO NOTHING;

-- Add columns to user_lens_context if they don't exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'user_lens_context' AND column_name = 'suggested_persona') THEN
    ALTER TABLE "user_lens_context" ADD COLUMN "suggested_persona" TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'user_lens_context' AND column_name = 'suggested_kb') THEN
    ALTER TABLE "user_lens_context" ADD COLUMN "suggested_kb" TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'user_lens_context' AND column_name = 'persona_reasoning') THEN
    ALTER TABLE "user_lens_context" ADD COLUMN "persona_reasoning" TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'user_lens_context' AND column_name = 'kb_reasoning') THEN
    ALTER TABLE "user_lens_context" ADD COLUMN "kb_reasoning" TEXT;
  END IF;
END $$;

-- Create indexes
CREATE INDEX IF NOT EXISTS "idx_kb_slug" ON "knowledge_bases" ("kb_slug");
CREATE INDEX IF NOT EXISTS "idx_kb_type" ON "knowledge_bases" ("kb_type");
CREATE INDEX IF NOT EXISTS "idx_kb_paradigm" ON "knowledge_bases" ("paradigm_family");
CREATE INDEX IF NOT EXISTS "idx_user_kb_user" ON "user_knowledge_access" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_prog_kb_prog" ON "programme_knowledge_map" ("programme_profile_id");

-- Success message
SELECT 'Personas and Knowledge Bases updated. ' || 
       (SELECT COUNT(*) FROM knowledge_bases) || ' knowledge bases, ' ||
       (SELECT COUNT(*) FROM archetypal_personas) || ' personas.' AS status;




