-- Supabase CREATE TABLE statements for 25 Notion databases
-- All column names are quoted for safety


-- system_manifest (9 rows)
CREATE TABLE IF NOT EXISTS "system_manifest" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "export_order" TEXT,
  "status" TEXT,
  "primary_key" TEXT,
  "canonical_name_confirmed" TEXT,
  "purpose" TEXT,
  "notes" TEXT,
  "depends_on" TEXT,
  "database" TEXT
);

-- attribute_taxonomy (76 rows)
CREATE TABLE IF NOT EXISTS "attribute_taxonomy" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "untitled_database" TEXT,
  "untitled_database_1" TEXT,
  "parent_attribute" TEXT,
  "rules___gating__db_" TEXT,
  "dashboard_blocks__db__1" TEXT,
  "dashboard_blocks__db_" TEXT,
  "session_templates__db_" TEXT,
  "attribute_role" TEXT,
  "attribute" TEXT,
  "role" TEXT,
  "parent" TEXT
);

-- programme_profiles (14 rows)
CREATE TABLE IF NOT EXISTS "programme_profiles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "session_templates__db____relation___session_templates__db___if_present_in_csv_" TEXT,
  "default_strictness___select" TEXT,
  "primary_doctrine___select" TEXT,
  "enabled_blocks___relation___dashboard_blocks__db_" TEXT,
  "secondary_attribute_focus___relation___attribute_taxonomy__db_" TEXT,
  "dashboard_blocks__db____relation___dashboard_blocks__db___if_present_in_csv_" TEXT,
  "default_depth___select" TEXT,
  "notes___text" TEXT,
  "primary_attribute_focus___relation___attribute_taxonomy__db_" TEXT,
  "programme_profile___title" TEXT
);

-- dashboard_blocks (19 rows)
CREATE TABLE IF NOT EXISTS "dashboard_blocks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "covers_attributes" TEXT,
  "linked_system" TEXT,
  "default_depth" TEXT,
  "rules_applied" TEXT,
  "linked_programme_profile_2" TEXT,
  "required_attributes" TEXT,
  "max_depth" TEXT,
  "settings" TEXT,
  "type" TEXT,
  "secondary_attribute_focus" TEXT,
  "display_depth" TEXT,
  "linked_programme_profile" TEXT,
  "primary_attribute_focus" TEXT,
  "default_strictness" TEXT,
  "column" TEXT,
  "default_frequency" TEXT,
  "block_type" TEXT
);

-- safety_rules (8 rows)
CREATE TABLE IF NOT EXISTS "safety_rules" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "description" TEXT,
  "applies_to" TEXT,
  "severity" TEXT,
  "untitled_database" TEXT,
  "rule_name" TEXT
);

-- nutrition_and_food (59 rows)
CREATE TABLE IF NOT EXISTS "nutrition_and_food" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "type" TEXT,
  "settings___relation" TEXT,
  "column_name" TEXT,
  "food_type" TEXT,
  "primary_nutrition_domain" TEXT,
  "associated_diets___protocols" TEXT,
  "evidence_confidence" TEXT,
  "secondary_nutrition_domains" TEXT,
  "notes" TEXT,
  "feeds_intake_items" TEXT,
  "relevant_supplement_interactions" TEXT
);

-- nutrition_intake (5 rows)
CREATE TABLE IF NOT EXISTS "nutrition_intake" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "notes" TEXT,
  "type" TEXT,
  "completion_type" TEXT,
  "linked_supplement" TEXT,
  "dashboard_blocks__db_" TEXT,
  "linked_nutrition_metric" TEXT,
  "intake_item" TEXT
);

-- supplement_interactions (14 rows)
CREATE TABLE IF NOT EXISTS "supplement_interactions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "type" TEXT,
  "settings" TEXT,
  "nutrition_intake__db_" TEXT,
  "evidence_note" TEXT,
  "column" TEXT,
  "b_supplement" TEXT,
  "do_not" TEXT,
  "a_supplement" TEXT,
  "do" TEXT,
  "interaction_type" TEXT,
  "strength" TEXT,
  "safety_flag" TEXT,
  "mechanism__short_" TEXT
);

-- mappings (10 rows)
CREATE TABLE IF NOT EXISTS "mappings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "direction" TEXT,
  "mapping_type" TEXT,
  "from_value" TEXT,
  "to_db" TEXT,
  "from_db" TEXT,
  "notes" TEXT,
  "to_value" TEXT,
  "mapping" TEXT,
  "to_field" TEXT,
  "from_field" TEXT
);

-- rules_gating (20 rows)
CREATE TABLE IF NOT EXISTS "rules_gating" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "dashboard_blocks__db_" TEXT,
  "breath_library__db_" TEXT,
  "blocked_elements" TEXT,
  "programme_profiles__db___" TEXT,
  "settings" TEXT,
  "threshold_parametre" TEXT,
  "required_persona_bias" TEXT,
  "allowed_breath_protocols" TEXT,
  "type" TEXT,
  "column_name" TEXT,
  "rule_type" TEXT,
  "applies_to" TEXT,
  "relates_to" TEXT,
  "max_level" TEXT,
  "operator" TEXT,
  "threshold_parameter" TEXT,
  "threshold_value" TEXT,
  "limit" TEXT,
  "two_way" TEXT,
  "min_level" TEXT,
  "action" TEXT,
  "trigger_attribute" TEXT,
  "priority" TEXT
);

-- breath_library (26 rows)
CREATE TABLE IF NOT EXISTS "breath_library" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "typical_use" TEXT,
  "notes" TEXT,
  "core_breath_quality" TEXT,
  "activation_level" TEXT,
  "primary_element" TEXT,
  "safety_tier" TEXT,
  "untitled_database" TEXT,
  "organ___systemprimary_emotionsecondary_emotionstress_expressionsomatic_manifestationprimary_elementsecondary_elementnervous_system_biasregulation_directioncontraindications___risk_notesnotesliverangerfrustration__irritabilityhyperactivationheat__tensionwood___airfiresympatheticsoothingavoid_aggressive_breathworktcm__flowheartjoyanxietydysregulationpalpitations__heatfireethermixedgroundingcardiac_sensitivitycenterlungsgriefsadnesssuppressionconstriction__fatigueairmetalparasympatheticactivatingbreath_sensitivityrespirationkidneysfearinsecuritysuppressioncold__weaknesswaterearthparasympatheticwarmingadrenal_fatiguesurvivalspleen___pancreasworryoverthinkingdysregulationheaviness__fatigueearthwatermixedgroundingdigestive_sensitivityassimilationstomachanxietynauseahyperactivationtightnessearthfiresympatheticsoothingeating_disordersprocessingintestinesletting_goshamesuppressioncrampingearthairparasympatheticintegrativeibsreleasegallbladderdecision_stressresentmenthyperactivationtensionwood__" TEXT,
  "safety_rules" TEXT,
  "contraindications" TEXT,
  "programme_profiles__db___" TEXT,
  "secondary_element" TEXT,
  "chakra_systems__db_" TEXT,
  "protocol_name" TEXT
);

-- movements_system (16 rows)
CREATE TABLE IF NOT EXISTS "movements_system" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "sound_pairing" TEXT,
  "contraindications___safety_notes" TEXT,
  "nadi_affinity" TEXT,
  "primary_body_region" TEXT,
  "tradition___lineage" TEXT,
  "programme_profiles__db___" TEXT,
  "primary_effect" TEXT,
  "secondary_element" TEXT,
  "organ_affinity" TEXT,
  "nervous_system_bias" TEXT,
  "untitled_database" TEXT,
  "movement_family" TEXT,
  "notes" TEXT,
  "recommended_persona_bias" TEXT,
  "meridian_affinity" TEXT,
  "light___colour_pairing" TEXT,
  "intensity" TEXT,
  "primary_element" TEXT,
  "intent___condition_fit" TEXT,
  "chakra_affinity" TEXT,
  "movement___practice" TEXT
);

-- session_types (6 rows)
CREATE TABLE IF NOT EXISTS "session_types" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "untitled_database" TEXT,
  "allows_activation" TEXT,
  "max_intensity" TEXT,
  "relevant_emotions" TEXT,
  "allowed_styles" TEXT,
  "notes" TEXT,
  "session_type" TEXT
);

-- sound_vibration (10 rows)
CREATE TABLE IF NOT EXISTS "sound_vibration" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "frequency__hz_" TEXT,
  "programme_profiles__db___" TEXT,
  "elemental_bias" TEXT,
  "meridian_affinity" TEXT,
  "archetypal_personas__db_" TEXT,
  "movements_system__db_" TEXT,
  "sound_type" TEXT,
  "untitled_database" TEXT,
  "nervous_system_bias" TEXT,
  "primary_organ" TEXT,
  "notes" TEXT,
  "chakra_affinity" TEXT,
  "contraindications___safety_notes" TEXT,
  "primary_effect" TEXT,
  "sound___frequency" TEXT
);

-- light_colour (43 rows)
CREATE TABLE IF NOT EXISTS "light_colour" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "contraindications___safety_notes" TEXT,
  "primary_effect" TEXT,
  "programme_profiles__db___" TEXT,
  "notes" TEXT,
  "colour_family" TEXT,
  "archetypal_personas__db_" TEXT,
  "elemental_bias" TEXT,
  "chakra_affinity" TEXT,
  "movements_system__db_" TEXT,
  "light___colour" TEXT,
  "psychological_theme" TEXT,
  "wavelength__nm_" TEXT,
  "circadian_influence" TEXT
);

-- symbols_index (94 rows)
CREATE TABLE IF NOT EXISTS "symbols_index" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "cultural_scope" TEXT,
  "organ___systemprimary_emotionsecondary_emotionstress_expressionsomatic_manifestationprimary_elementsecondary_elementnervous_system_biasregulation_directioncontraindications___risk_notesnotesliverangerfrustration__irritabilityhyperactivationheat__tensionwood___airfiresympatheticsoothingavoid_aggressive_breathworktcm__flowheartjoyanxietydysregulationpalpitations__heatfireethermixedgroundingcardiac_sensitivitycenterlungsgriefsadnesssuppressionconstriction__fatigueairmetalparasympatheticactivatingbreath_sensitivityrespirationkidneysfearinsecuritysuppressioncold__weaknesswaterearthparasympatheticwarmingadrenal_fatiguesurvivalspleen___pancreasworryoverthinkingdysregulationheaviness__fatigueearthwatermixedgroundingdigestive_sensitivityassimilationstomachanxietynauseahyperactivationtightnessearthfiresympatheticsoothingeating_disordersprocessingintestinesletting_goshamesuppressioncrampingearthairparasympatheticintegrativeibsreleasegallbladderdecision_stressresentmenthyperactivationtensionwood__" TEXT,
  "sacred_geometry" TEXT,
  "secondary_element" TEXT,
  "untitled_database" TEXT,
  "programme_profiles__db___" TEXT,
  "primary_element" TEXT,
  "archetypal_personas__db_" TEXT,
  "meaning_domain" TEXT,
  "stones" TEXT,
  "emotional_tone" TEXT,
  "mythology" TEXT,
  "symbol_class" TEXT,
  "nadi_system__db_" TEXT,
  "chakra_systems__db_" TEXT,
  "astrological_archetype" TEXT,
  "sacred_animal" TEXT,
  "symbol" TEXT,
  "notes" TEXT
);

-- sacred_geometry (21 rows)
CREATE TABLE IF NOT EXISTS "sacred_geometry" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "secondary_element" TEXT,
  "notes" TEXT,
  "symbols_index__db_" TEXT,
  "psychophysiological_effect" TEXT,
  "untitled_database" TEXT,
  "primary_element" TEXT,
  "cultural_lineage" TEXT,
  "risk___contraindications" TEXT,
  "dimensional_emphasis" TEXT,
  "primary_function" TEXT,
  "geometry_class" TEXT,
  "geometry" TEXT
);

-- deities_archetypes (55 rows)
CREATE TABLE IF NOT EXISTS "deities_archetypes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "primary_domain" TEXT,
  "type" TEXT,
  "associated_colours" TEXT,
  "sacred_geometry" TEXT,
  "sound_mantra_seed" TEXT,
  "culture_lineage" TEXT,
  "notes" TEXT,
  "key_symbols" TEXT,
  "secondary_domains" TEXT,
  "risk_tag" TEXT,
  "untitled_database" TEXT,
  "name" TEXT
);

-- elemental_framework (19 rows)
CREATE TABLE IF NOT EXISTS "elemental_framework" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "notes" TEXT,
  "risk_profile" TEXT,
  "core_qualities" TEXT,
  "emotional_tone" TEXT,
  "alternate_names___systems" TEXT,
  "physiological_correlates" TEXT,
  "nervous_system_bias" TEXT,
  "typical_functions" TEXT,
  "element" TEXT
);

-- organ_emotion_system (15 rows)
CREATE TABLE IF NOT EXISTS "organ_emotion_system" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "secondary_element" TEXT,
  "regulation_direction" TEXT,
  "intent___condition_framework__db_" TEXT,
  "chakra_systems__db__1" TEXT,
  "nervous_system_bias" TEXT,
  "notes" TEXT,
  "meridian_system__db_" TEXT,
  "breath_type" TEXT,
  "intent___condition_framework__db__1" TEXT,
  "primary_emotion" TEXT,
  "movements_system__db_" TEXT,
  "contraindications___risk_notes" TEXT,
  "secondary_emotion" TEXT,
  "somatic_manifestation" TEXT,
  "stress_expression" TEXT,
  "primary_element" TEXT,
  "chakra_systems__db_" TEXT,
  "sound___vibration_system__db_" TEXT,
  "untitled_database" TEXT,
  "symbol" TEXT,
  "organ___system" TEXT
);

-- nutrition_protocols (12 rows)
CREATE TABLE IF NOT EXISTS "nutrition_protocols" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "strictness_level" TEXT,
  "secondary_attribute_focus" TEXT,
  "notes" TEXT,
  "included_food" TEXT,
  "primary_nutrition_goal" TEXT,
  "primary_attribute_focus" TEXT,
  "nutrition_protocol" TEXT
);

-- session_templates (19 rows)
CREATE TABLE IF NOT EXISTS "session_templates" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "settings" TEXT,
  "type" TEXT,
  "column_name" TEXT,
  "secondary_intents____nl_" TEXT,
  "primary_intent____l1_" TEXT,
  "pause_style" TEXT,
  "session_type____l1_" TEXT,
  "style____nl_" TEXT,
  "movements____nl_" TEXT,
  "default_duration__min_" TEXT,
  "notes" TEXT,
  "safety_rules____nl_" TEXT,
  "breath_protocols____nl_" TEXT,
  "script_strictness" TEXT
);

-- archetypal_personas (10 rows)
CREATE TABLE IF NOT EXISTS "archetypal_personas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "programme_profiles__db___" TEXT,
  "metaphor_density" TEXT,
  "preferred_styles" TEXT,
  "symbol_affinity" TEXT,
  "sound_affinity" TEXT,
  "cognitive_style" TEXT,
  "language_tone" TEXT,
  "nervous_system_bias" TEXT,
  "tradition_affinity" TEXT,
  "contraindications___risk_notes" TEXT,
  "notes" TEXT,
  "lineage___influence" TEXT,
  "safety_profile" TEXT,
  "light_colour" TEXT,
  "primary_use_context" TEXT,
  "persona" TEXT
);

-- chakra_systems (7 rows)
CREATE TABLE IF NOT EXISTS "chakra_systems" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "dysregulation_signs" TEXT,
  "primary_element" TEXT,
  "movements_system__db_" TEXT,
  "symbol" TEXT,
  "sound___vibration_system__db_" TEXT,
  "organ_emotion" TEXT,
  "sanskrit_name" TEXT,
  "secondary_element" TEXT,
  "location__somatic_" TEXT,
  "regulation_direction" TEXT,
  "nadi_system__db_" TEXT,
  "contraindications___safety_notes" TEXT,
  "notes" TEXT,
  "nervous_system_bias" TEXT,
  "untitled_database_1" TEXT,
  "physiological_correlates" TEXT,
  "untitled_database" TEXT,
  "breath_type" TEXT,
  "psychological_function" TEXT,
  "chakra" TEXT
);

-- meridian_system (12 rows)
CREATE TABLE IF NOT EXISTS "meridian_system" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT,
  "regulation_direction" TEXT,
  "movements_system__db_" TEXT,
  "secondary_emotional_themes" TEXT,
  "associated_organ" TEXT,
  "somatic_pathway" TEXT,
  "notes" TEXT,
  "primary_emotion" TEXT,
  "yin___yang" TEXT,
  "sound___vibration_system__db_" TEXT,
  "five_element_phase" TEXT,
  "nervous_system_bias" TEXT,
  "untitled_database" TEXT,
  "contraindications___safety_notes" TEXT,
  "physiological_emphasis" TEXT,
  "meridian" TEXT
);
