-- Workbook-aligned seeds from database_builder_actual_tables_only.xlsx
-- This preserves the catalogue layer and keeps unresolved ingredient/protocol matches explicit.

INSERT INTO branch_nodes (
  branch_id,
  parent_branch_id,
  branch_name,
  branch_slug,
  branch_scope_type,
  branch_status,
  notes
)
VALUES
  ('branch_brazil', NULL, 'Brazil', 'brazil', 'country_program', 'planned_live', 'Initial live branch / region from current handover'),
  ('branch_united_kingdom', NULL, 'United Kingdom', 'united_kingdom', 'country_program', 'planned_live', 'Initial live branch / region from current handover'),
  ('branch_north_africa', NULL, 'North Africa', 'north_africa', 'regional_cluster', 'planned_live', 'Initial live branch / region from current handover')
ON CONFLICT (branch_id) DO UPDATE SET
  branch_name = EXCLUDED.branch_name,
  branch_slug = EXCLUDED.branch_slug,
  branch_scope_type = EXCLUDED.branch_scope_type,
  branch_status = EXCLUDED.branch_status,
  notes = EXCLUDED.notes,
  updated_at = NOW();

INSERT INTO ferment_family (
  ferment_family_id,
  ferment_family_name,
  status,
  sweetener_base_current_export,
  tea_base_current_export,
  target_temp_c_current_export,
  notes
)
VALUES
  ('ferment_family_jun', 'Jun', 'actual_in_export', 'honey', 'not explicitly stated in export', '22-26 (core ferment); <10 (freeze); 30-35 (dry/reduce)', 'Use this table to distinguish base ferment families if Kombucha is merged into one catalogue later.'),
  ('ferment_family_kombucha', 'Kombucha', 'not_proven_in_current_export', '', '', '', 'Reserved differentiator row only. Do not load fake Kombucha product or protocol rows unless source data arrives.'),
  ('ferment_family_scoby_derivative', 'SCOBY derivative', 'actual_product_base_in_export', 'inherits from upstream ferment source', 'inherits from upstream ferment source', 'depends on upstream ferment + drying workflow', 'Current product rows use SCOBY Mass as a core base, but the export does not prove whether each row came from Jun-only or Kombucha-only SCOBY.')
ON CONFLICT (ferment_family_id) DO UPDATE SET
  ferment_family_name = EXCLUDED.ferment_family_name,
  status = EXCLUDED.status,
  sweetener_base_current_export = EXCLUDED.sweetener_base_current_export,
  tea_base_current_export = EXCLUDED.tea_base_current_export,
  target_temp_c_current_export = EXCLUDED.target_temp_c_current_export,
  notes = EXCLUDED.notes,
  updated_at = NOW();

INSERT INTO botanical_entries_master (
  botanical_entry_id,
  botanical_name,
  duplicate_name_group,
  duplicate_name_count,
  part_used,
  season,
  ferment_safety,
  use_type,
  functions,
  form_in_system,
  micronutrients,
  notes,
  ayurvedic_profile,
  tcm_meridians,
  tcm_nature_flavour,
  archetype_animal,
  scientific_actions,
  synergy_tags,
  element_planet,
  permaculture_guild,
  biodynamic_timing,
  soil_type,
  growing_conditions,
  foraging_habitat,
  kombucha_1f_friendly_flag,
  tea_friendly_flag,
  bitters_friendly_flag,
  cordial_friendly_flag,
  fresh_produce_friendly_flag,
  preserve_friendly_flag,
  cosmetic_friendly_flag,
  source_table,
  source_row
)
VALUES
  ('bot_nettle_leaf', 'Nettle Leaf', 'nettle_leaf', 1, 'Leaf', 'Mar;Apr;May;', 'Primary OK', 'Tea;Nutrient;Tonic', 'Detox;Blood-building;Anti-inflammatory;Energy', 'Dried;Cold Extract;Fresh', 'Iron;Calcium;Magnesium;Silica;Vit C;Vit K', 'Use young leaves; very good base herb', 'Vata-grounding;Pitta-slightly up;Kapha-down', 'Liver;Kidney;Blood', 'Slightly warm;Green;Slightly bitter;Slightly salty', 'Ox;Dragon', 'Nutrient-dense tonic;diuretic;anti-inflammatory;antihistamine tendency', 'Liver/Detox;Blood-Building;Post-Sport Recovery;General Tonic;Mineral Support', 'Earth;Mars;Saturn', 'Dynamic accumulator;Edge species;Soil improver', 'Leaf Day;Waxing Moon;Ascending Moon;Moon in Taurus;Moon in Virgo', 'Loam;Clay;Rich;Disturbed Ground', 'Full Sun;Partial Shade', 'Field edges;hedges;disturbed soil;garden edges', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Botanical list (kombucha friendly)', 1),
  ('bot_chickweed', 'Chickweed', 'chickweed', 2, 'Leaf', 'Mar;Apr;May;', 'Primary OK', 'Greens;Tea', 'Cooling;Skin support;Mild detox', 'Fresh;Dried', 'Vit C;Minerals', 'Very mild; great raw or as gentle spring tea', 'Pitta-reducing;Vata-soothing;Kapha-neutral', 'Lung;Skin', 'Cool;Mild;Slightly salty', 'Mouse;Hare', 'Emollient;anti-inflammatory;soothing', 'Skin/Topical;Gentle Detox;Spring Cleanse', 'Water;Moon', 'Groundcover;Living mulch', 'Leaf Day;Waning Moon;Descending Moon;Moon in Cancer', 'Moist Loam;Rich;Garden soil', 'Partial Shade;Full Sun (cool sites)', 'Gardens;path edges;beds;moist disturbed soil', TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, 'Botanical list (kombucha friendly)', 2),
  ('bot_cleavers', 'Cleavers', 'cleavers', 1, 'Leaf', 'Mar;Apr;May;', 'Primary OK', 'Tea;Tonic', 'Lymph support;Detox;Diuretic', 'Fresh;Cold Extract;Dried', 'Vit C;Minerals', 'Best as fresh/cold maceration; classic spring cleanser', 'Pitta-reducing;Kapha-reducing;Vata-neutral', 'Lymph;Urinary (Bladder);Skin', 'Cool;Green;Slightly bitter', 'Deer;Hare', 'Lymphagogue;diuretic;mild depurative', 'Lymph/Detox;Skin;Spring Cleanse', 'Water;Moon', 'Hedgerow creeper;Living trellis plant', 'Leaf Day;Waning Moon;Descending Moon;Moon in Pisces', 'Moist;Hedgerow;Rich', 'Partial Shade', 'Hedgerows;ditch lines;fence lines', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Botanical list (kombucha friendly)', 3),
  ('bot_ginger_wild_or_garden', 'Ginger (wild or garden)', 'ginger_wild_or_garden', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 'Botanical list (kombucha friendly)', 999)
ON CONFLICT (botanical_entry_id) DO UPDATE SET
  botanical_name = EXCLUDED.botanical_name,
  duplicate_name_group = EXCLUDED.duplicate_name_group,
  duplicate_name_count = EXCLUDED.duplicate_name_count,
  part_used = EXCLUDED.part_used,
  season = EXCLUDED.season,
  ferment_safety = EXCLUDED.ferment_safety,
  use_type = EXCLUDED.use_type,
  functions = EXCLUDED.functions,
  form_in_system = EXCLUDED.form_in_system,
  micronutrients = EXCLUDED.micronutrients,
  notes = EXCLUDED.notes,
  ayurvedic_profile = EXCLUDED.ayurvedic_profile,
  tcm_meridians = EXCLUDED.tcm_meridians,
  tcm_nature_flavour = EXCLUDED.tcm_nature_flavour,
  archetype_animal = EXCLUDED.archetype_animal,
  scientific_actions = EXCLUDED.scientific_actions,
  synergy_tags = EXCLUDED.synergy_tags,
  element_planet = EXCLUDED.element_planet,
  permaculture_guild = EXCLUDED.permaculture_guild,
  biodynamic_timing = EXCLUDED.biodynamic_timing,
  soil_type = EXCLUDED.soil_type,
  growing_conditions = EXCLUDED.growing_conditions,
  foraging_habitat = EXCLUDED.foraging_habitat,
  kombucha_1f_friendly_flag = EXCLUDED.kombucha_1f_friendly_flag,
  tea_friendly_flag = EXCLUDED.tea_friendly_flag,
  bitters_friendly_flag = EXCLUDED.bitters_friendly_flag,
  cordial_friendly_flag = EXCLUDED.cordial_friendly_flag,
  fresh_produce_friendly_flag = EXCLUDED.fresh_produce_friendly_flag,
  preserve_friendly_flag = EXCLUDED.preserve_friendly_flag,
  cosmetic_friendly_flag = EXCLUDED.cosmetic_friendly_flag,
  source_table = EXCLUDED.source_table,
  source_row = EXCLUDED.source_row,
  updated_at = NOW();

INSERT INTO botanical_zone_profiles (
  zone_profile_id,
  botanical_entry_id,
  match_status,
  match_candidates,
  botanical_link,
  common_names,
  growth_habit,
  forest_garden_layer,
  lifespan,
  native_region,
  climate_band_prefers,
  hardiness_class,
  outdoor_suitability,
  greenhouse_zone,
  indoor_container_use,
  soil_type,
  soil_moisture,
  soil_functions,
  sun_exposure,
  humidity_preference,
  root_depth_type,
  spread_pattern,
  companion_plants,
  incompatible_with,
  guild_roles,
  foraging_habitat,
  harvest_window,
  planting_sowing_window,
  yield_regrowth,
  propagation_methods,
  conservation_status,
  foraging_cautions,
  wildlife_supported,
  notes,
  branch_id,
  country,
  region,
  zone,
  microclimate_tags,
  production_mode,
  source_table,
  source_row
)
VALUES
  ('zone_001_nettle_leaf', NULL, 'ambiguous', 'bot_nettle_leaf:Nettle Leaf | bot_nettle_root:Nettle Root', 'Nettle Leaf', 'Stinging Nettle', 'Herb', 'Herbaceous', 'Perennial', 'UK;Europe', 'Cool Temperate;Mild Temperate', 'Very Hardy', 'Woodland Edge;Hedgerow;Meadow', 'Cool House', 'Large Pot', 'Loam;Rich;Moist', 'Moist', 'Dynamic Accumulator (N,K,Fe)', 'Full Sun;Partial Shade', 'Moderate', 'Deep fibrous', 'Colonising', 'Fruit trees;Comfrey;Currants', 'Brassicas', 'Nutrient Pump', 'Hedgerow;Woodland Edge;Meadow', 'Mar-Oct', 'Feb-Apr (seed); Mar-May (division)', 'Fast regrowth', 'Division;Seed', 'Abundant', 'Can sting', 'Bees;Butterflies', 'Cut regularly for tender leaves', NULL, NULL, NULL, NULL, NULL, NULL, 'GROWING & HARVESTING', 1),
  ('zone_002_chickweed', NULL, 'ambiguous', 'bot_chickweed:Chickweed | bot_chickweed__2:Chickweed', 'Chickweed', 'Chickweed', 'Herb', 'Groundcover', 'Annual', 'Europe', 'Cool Temperate', 'Hardy', 'Garden beds;Woodland edge', 'Cool House', 'Windowsill', 'Loam;Moist', 'Moist', 'Ground stabiliser', 'Shade;Partial Shade', 'Moderate', 'Shallow fibrous', 'Clumping', 'Brassicas;Leafy greens', '-', 'Groundcover', 'Lawns;Edges', 'Feb-Oct', 'Aug-Mar (cool season)', 'Very fast regrowth', 'Seed;Self-seeding', 'Abundant', 'Avoid polluted edges', 'Bees', 'Winter herb in mild climates', NULL, NULL, NULL, NULL, NULL, NULL, 'GROWING & HARVESTING', 2),
  ('zone_003_plantain_leaf', NULL, 'ambiguous', 'bot_plantain_leaf_ribwort_broadleaf:Plantain Leaf (Ribwort/Broadleaf) | bot_plantain_narrowleaf:Plantain (narrowleaf)', 'Plantain Leaf', 'Ribwort Plantain', 'Herb', 'Groundcover', 'Perennial', 'Europe', 'Cool Temperate', 'Very Hardy', 'Meadows;Pathsides', 'Cool House', 'Large Pot', 'Poor;Loam;Sandy', 'Dry-Moist', 'Soil binder', 'Full Sun;Partial Shade', 'Dry air', 'Deep taproot', 'Clumping', 'Lawns;Meadow plants', '-', 'Soil stabiliser', 'Everywhere', 'Apr-Oct', 'Mar-May (seed); Autumn (division)', 'Good regrowth', 'Seed', 'Abundant', NULL, 'Bees', 'Thrives in poor soil', NULL, NULL, NULL, NULL, NULL, NULL, 'GROWING & HARVESTING', 3)
ON CONFLICT (zone_profile_id) DO UPDATE SET
  botanical_entry_id = EXCLUDED.botanical_entry_id,
  match_status = EXCLUDED.match_status,
  match_candidates = EXCLUDED.match_candidates,
  botanical_link = EXCLUDED.botanical_link,
  common_names = EXCLUDED.common_names,
  growth_habit = EXCLUDED.growth_habit,
  forest_garden_layer = EXCLUDED.forest_garden_layer,
  lifespan = EXCLUDED.lifespan,
  native_region = EXCLUDED.native_region,
  climate_band_prefers = EXCLUDED.climate_band_prefers,
  hardiness_class = EXCLUDED.hardiness_class,
  outdoor_suitability = EXCLUDED.outdoor_suitability,
  greenhouse_zone = EXCLUDED.greenhouse_zone,
  indoor_container_use = EXCLUDED.indoor_container_use,
  soil_type = EXCLUDED.soil_type,
  soil_moisture = EXCLUDED.soil_moisture,
  soil_functions = EXCLUDED.soil_functions,
  sun_exposure = EXCLUDED.sun_exposure,
  humidity_preference = EXCLUDED.humidity_preference,
  root_depth_type = EXCLUDED.root_depth_type,
  spread_pattern = EXCLUDED.spread_pattern,
  companion_plants = EXCLUDED.companion_plants,
  incompatible_with = EXCLUDED.incompatible_with,
  guild_roles = EXCLUDED.guild_roles,
  foraging_habitat = EXCLUDED.foraging_habitat,
  harvest_window = EXCLUDED.harvest_window,
  planting_sowing_window = EXCLUDED.planting_sowing_window,
  yield_regrowth = EXCLUDED.yield_regrowth,
  propagation_methods = EXCLUDED.propagation_methods,
  conservation_status = EXCLUDED.conservation_status,
  foraging_cautions = EXCLUDED.foraging_cautions,
  wildlife_supported = EXCLUDED.wildlife_supported,
  notes = EXCLUDED.notes,
  branch_id = EXCLUDED.branch_id,
  country = EXCLUDED.country,
  region = EXCLUDED.region,
  zone = EXCLUDED.zone,
  microclimate_tags = EXCLUDED.microclimate_tags,
  production_mode = EXCLUDED.production_mode,
  source_table = EXCLUDED.source_table,
  source_row = EXCLUDED.source_row,
  updated_at = NOW();

INSERT INTO protocol_library (
  protocol_id,
  protocol_name,
  protocol_family,
  stage,
  batch_size_l,
  tea_ratio_g_l,
  sugar_honey_g_l,
  culture_pct_vv,
  target_temp_c,
  ferment_time_days,
  output_form,
  live_cultures,
  intended_next_step,
  linked_product_use,
  notes,
  target_temp_c_min,
  target_temp_c_max,
  tea_ratio_g_l_min,
  tea_ratio_g_l_max,
  sugar_honey_g_l_min,
  sugar_honey_g_l_max,
  culture_pct_vv_min,
  culture_pct_vv_max,
  source_table,
  source_row
)
VALUES
  ('prot_jun_core_ferment_v1', 'Jun - Core Ferment v1', 'ferment_family_jun', 'Primary', '4', '8-10', '70-80 (honey)', '15-20', '22-26', '7-10', 'Liquid', 'Yes (full)', 'Concentrate', 'Base for all concentrates/powder', 'Slightly over-fermented; aim for sour, low-sugar', 22, 26, 8, 10, 70, 80, 15, 20, 'Brew Ferment Protocols', 1),
  ('prot_jun_freeze_concentration_v1', 'Jun - Freeze Concentration v1', 'ferment_family_jun', 'Concentration', '4 -> 1.5', '-', '-', '-', '<10 (freezer)', '1-2 (freeze + thaw)', 'Concentrate', 'Yes (full)', 'Low-temp Dry or 2F', 'Strong liquid for powder/gel', 'Collect first 30-50% of melt for 2-3x strength', NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, 'Brew Ferment Protocols', 2),
  ('prot_jun_low_temp_tray_reduce_v1', 'Jun - Low-Temp Tray Reduce v1', 'ferment_family_jun', 'Concentration', '1.5 -> 0.7', '-', '-', '-', '30-35', '3-6 (hours)', 'Syrup', 'Yes (partial)', 'Mix with carrier & dry', 'Input for low-temp powder', 'Spread thin; keep actual syrup under about 35-40C', 30, 35, NULL, NULL, NULL, NULL, NULL, NULL, 'Brew Ferment Protocols', 3),
  ('prot_jun_powder_dry_v1', 'Jun - Powder Dry v1', 'ferment_family_jun', 'Drying', '0.7 (syrup)', '-', '-', '-', '30-35', '6-12 (hours)', 'Powder', 'Partial', 'SCOBY test / Product', 'Core live Jun powder', 'Syrup + inulin/acacia; dry till brittle/leathery', 30, 35, NULL, NULL, NULL, NULL, NULL, NULL, 'Brew Ferment Protocols', 4),
  ('prot_jun_scoby_regrowth_test_v1', 'Jun - SCOBY Regrowth Test v1', 'ferment_family_jun', 'Test / QA', '0.25-0.5', '8-10', '70-80 (honey)', '-', '22-26', '7-14', 'Liquid + pellicle', 'Yes (full if successful)', 'Validate powder as starter', 'Validate live, regenerative powder', 'Powder added to fresh sweet tea; watch pH and pellicle', 22, 26, 8, 10, 70, 80, NULL, NULL, 'Brew Ferment Protocols', 5)
ON CONFLICT (protocol_id) DO UPDATE SET
  protocol_name = EXCLUDED.protocol_name,
  protocol_family = EXCLUDED.protocol_family,
  stage = EXCLUDED.stage,
  batch_size_l = EXCLUDED.batch_size_l,
  tea_ratio_g_l = EXCLUDED.tea_ratio_g_l,
  sugar_honey_g_l = EXCLUDED.sugar_honey_g_l,
  culture_pct_vv = EXCLUDED.culture_pct_vv,
  target_temp_c = EXCLUDED.target_temp_c,
  ferment_time_days = EXCLUDED.ferment_time_days,
  output_form = EXCLUDED.output_form,
  live_cultures = EXCLUDED.live_cultures,
  intended_next_step = EXCLUDED.intended_next_step,
  linked_product_use = EXCLUDED.linked_product_use,
  notes = EXCLUDED.notes,
  target_temp_c_min = EXCLUDED.target_temp_c_min,
  target_temp_c_max = EXCLUDED.target_temp_c_max,
  tea_ratio_g_l_min = EXCLUDED.tea_ratio_g_l_min,
  tea_ratio_g_l_max = EXCLUDED.tea_ratio_g_l_max,
  sugar_honey_g_l_min = EXCLUDED.sugar_honey_g_l_min,
  sugar_honey_g_l_max = EXCLUDED.sugar_honey_g_l_max,
  culture_pct_vv_min = EXCLUDED.culture_pct_vv_min,
  culture_pct_vv_max = EXCLUDED.culture_pct_vv_max,
  source_table = EXCLUDED.source_table,
  source_row = EXCLUDED.source_row,
  updated_at = NOW();

INSERT INTO product_catalogue (
  product_id,
  product_name,
  catalogue_line_guess,
  fermentation_family_guess,
  format_label,
  function_label,
  core_base,
  protocols_used,
  botanicals_used,
  live_status,
  intended_use,
  strength_level,
  shelf_stability,
  development_status,
  notes,
  source_table,
  source_row
)
VALUES
  ('prod_core_jun_powder_neutral', 'Core Jun Powder - Neutral', 'jun_powder', 'ferment_family_jun', 'Powder', 'General Wellness', 'Jun Powder', 'Powder Dry v1; Core Ferment v1', '(None essential - base product)', 'Live Culture', 'Base powder for all products', 'Standard', 'Ambient Stable', 'Tested', 'This is your master base ingredient', 'PRODUCT CATALOGUE', 1),
  ('prod_concentrated_jun_syrup_3x', 'Concentrated Jun Syrup - 3x', 'jun_syrup', 'ferment_family_jun', 'Syrup', 'Wellness', 'Jun Syrup', 'Freeze Concentration v1; Low-Temp Reduce v1', '(Optional additions via extracts)', 'Partial Live', 'Concentrate for gels & shots', 'Strong', 'Refrigerated', 'Prototype', 'Sour, thick, excellent for gels', 'PRODUCT CATALOGUE', 2),
  ('prod_pre_sport_gel_cacao_maca', 'Pre-Sport Gel - Cacao/Maca', 'jun_powder', 'ferment_family_jun', 'Gel', 'Energy', 'Jun Powder', 'Powder Dry v1', 'Cacao; Maca; Ginger; Citrus Peel', 'Partial Live', 'Pre-workout booster', 'Standard', 'Refrigerated', 'In Design', 'Functional gel using non-fermentables', 'PRODUCT CATALOGUE', 3),
  ('prod_post_sport_recovery_gel', 'Post-Sport Recovery Gel', 'jun_powder', 'ferment_family_jun', 'Gel', 'Recovery', 'Jun Powder', 'Powder Dry v1', 'Turmeric; Rosehip; Nettle; Ginger', 'Partial Live', 'Anti-inflammatory recovery', 'Standard', 'Refrigerated', 'Idea', 'Anti-inflammatory formula', 'PRODUCT CATALOGUE', 4),
  ('prod_night_calm_gel_rose_ashwagandha', 'Night Calm Gel - Rose/Ashwagandha', 'jun_powder', 'ferment_family_jun', 'Gel', 'Calm', 'Jun Powder', 'Powder Dry v1', 'Rose Petals; Ashwagandha; Lemon Balm', 'Partial Live', 'Nighttime relaxation', 'Mild', 'Refrigerated', 'In Design', 'Evening calm blend', 'PRODUCT CATALOGUE', 5),
  ('prod_aphrodisiac_gel_damiana_rose', 'Aphrodisiac Gel - Damiana/Rose', 'jun_powder', 'ferment_family_jun', 'Gel', 'Aphrodisiac', 'Jun Powder', 'Powder Dry v1', 'Damiana; Rose Petals; Vanilla (extract)', 'Partial Live', 'Mood/aphrodisiac', 'Standard', 'Refrigerated', 'Idea', 'Sensual floral base', 'PRODUCT CATALOGUE', 6),
  ('prod_scoby_fruit_leather_raspberry_hibiscus', 'SCOBY Fruit Leather - Raspberry/Hibiscus', 'scoby_derivative', 'ferment_family_scoby_derivative', 'Sweet', 'Digestive', 'SCOBY Mass', 'SCOBY Drying Protocol (later)', 'Raspberry; Hibiscus', 'Non-Live', 'Healthy sweet/snack', 'Standard', 'Ambient Stable', 'Prototype', 'SCOBY used as base for fruit leather', 'PRODUCT CATALOGUE', 7),
  ('prod_scoby_sour_strips', 'SCOBY Sour Strips', 'scoby_derivative', 'ferment_family_scoby_derivative', 'Sweet', 'Digestive', 'SCOBY Mass', 'SCOBY Drying Protocol', 'Citric acid; Berry powders', 'Non-Live', 'Sour healthy sweet', 'Strong', 'Ambient Stable', 'Idea', 'Kombucha-style sour candy', 'PRODUCT CATALOGUE', 8),
  ('prod_starter_kit_jun_regeneration_powder', 'Starter Kit - Jun Regeneration Powder', 'jun_powder', 'ferment_family_jun', 'Starter', 'Wellness', 'Jun Powder', 'Powder Dry v1; SCOBY Regrowth Test v1', '(None essential)', 'Live Culture', 'Rebuild new SCOBY from powder', 'Standard', 'Ambient Stable', 'Tested', 'Powder that regenerates SCOBY', 'PRODUCT CATALOGUE', 9),
  ('prod_enzyme_bitters_gentian_koji', 'Enzyme Bitters - Gentian/Koji', 'bitters_base', 'ferment_family_kombucha', 'Liquid', 'Digestive', 'Bitters Base', 'Vacuum Distillation v1 (Advanced)', 'Gentian; Angelica; Koji rice', 'Enzyme-Active', 'Digestive bitters with enzymes', 'Strong', 'Long-Term Stable', 'Idea', 'High-ABV, non-live enzyme-driven', 'PRODUCT CATALOGUE', 10)
ON CONFLICT (product_id) DO UPDATE SET
  product_name = EXCLUDED.product_name,
  catalogue_line_guess = EXCLUDED.catalogue_line_guess,
  fermentation_family_guess = EXCLUDED.fermentation_family_guess,
  format_label = EXCLUDED.format_label,
  function_label = EXCLUDED.function_label,
  core_base = EXCLUDED.core_base,
  protocols_used = EXCLUDED.protocols_used,
  botanicals_used = EXCLUDED.botanicals_used,
  live_status = EXCLUDED.live_status,
  intended_use = EXCLUDED.intended_use,
  strength_level = EXCLUDED.strength_level,
  shelf_stability = EXCLUDED.shelf_stability,
  development_status = EXCLUDED.development_status,
  notes = EXCLUDED.notes,
  source_table = EXCLUDED.source_table,
  source_row = EXCLUDED.source_row,
  updated_at = NOW();

INSERT INTO product_protocol_links (
  product_id,
  product_name,
  protocol_ref_label,
  protocol_id,
  matched_protocol_name,
  match_status
)
VALUES
  ('prod_core_jun_powder_neutral', 'Core Jun Powder - Neutral', 'Powder Dry v1', 'prot_jun_powder_dry_v1', 'Jun - Powder Dry v1', 'matched'),
  ('prod_core_jun_powder_neutral', 'Core Jun Powder - Neutral', 'Core Ferment v1', 'prot_jun_core_ferment_v1', 'Jun - Core Ferment v1', 'matched'),
  ('prod_concentrated_jun_syrup_3x', 'Concentrated Jun Syrup - 3x', 'Freeze Concentration v1', 'prot_jun_freeze_concentration_v1', 'Jun - Freeze Concentration v1', 'matched'),
  ('prod_concentrated_jun_syrup_3x', 'Concentrated Jun Syrup - 3x', 'Low-Temp Reduce v1', NULL, NULL, 'missing_in_protocol_export'),
  ('prod_pre_sport_gel_cacao_maca', 'Pre-Sport Gel - Cacao/Maca', 'Powder Dry v1', 'prot_jun_powder_dry_v1', 'Jun - Powder Dry v1', 'matched'),
  ('prod_post_sport_recovery_gel', 'Post-Sport Recovery Gel', 'Powder Dry v1', 'prot_jun_powder_dry_v1', 'Jun - Powder Dry v1', 'matched'),
  ('prod_night_calm_gel_rose_ashwagandha', 'Night Calm Gel - Rose/Ashwagandha', 'Powder Dry v1', 'prot_jun_powder_dry_v1', 'Jun - Powder Dry v1', 'matched'),
  ('prod_aphrodisiac_gel_damiana_rose', 'Aphrodisiac Gel - Damiana/Rose', 'Powder Dry v1', 'prot_jun_powder_dry_v1', 'Jun - Powder Dry v1', 'matched'),
  ('prod_scoby_fruit_leather_raspberry_hibiscus', 'SCOBY Fruit Leather - Raspberry/Hibiscus', 'SCOBY Drying Protocol (later)', NULL, NULL, 'missing_in_protocol_export'),
  ('prod_scoby_sour_strips', 'SCOBY Sour Strips', 'SCOBY Drying Protocol', NULL, NULL, 'missing_in_protocol_export'),
  ('prod_starter_kit_jun_regeneration_powder', 'Starter Kit - Jun Regeneration Powder', 'Powder Dry v1', 'prot_jun_powder_dry_v1', 'Jun - Powder Dry v1', 'matched'),
  ('prod_starter_kit_jun_regeneration_powder', 'Starter Kit - Jun Regeneration Powder', 'SCOBY Regrowth Test v1', 'prot_jun_scoby_regrowth_test_v1', 'Jun - SCOBY Regrowth Test v1', 'matched'),
  ('prod_enzyme_bitters_gentian_koji', 'Enzyme Bitters - Gentian/Koji', 'Vacuum Distillation v1 (Advanced)', NULL, NULL, 'missing_in_protocol_export')
ON CONFLICT (product_id, protocol_ref_label) DO UPDATE SET
  protocol_id = EXCLUDED.protocol_id,
  matched_protocol_name = EXCLUDED.matched_protocol_name,
  match_status = EXCLUDED.match_status;

INSERT INTO product_botanical_links (
  product_id,
  product_name,
  ingredient_label,
  ingredient_kind,
  botanical_entry_id,
  matched_botanical_name,
  match_status,
  candidate_matches,
  resolution_needed
)
VALUES
  ('prod_pre_sport_gel_cacao_maca', 'Pre-Sport Gel - Cacao/Maca', 'Cacao', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_pre_sport_gel_cacao_maca', 'Pre-Sport Gel - Cacao/Maca', 'Maca', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_pre_sport_gel_cacao_maca', 'Pre-Sport Gel - Cacao/Maca', 'Ginger', 'botanical_candidate', 'bot_ginger_wild_or_garden', 'Ginger (wild or garden)', 'matched_unique', 'bot_ginger_wild_or_garden:Ginger (wild or garden)', FALSE),
  ('prod_pre_sport_gel_cacao_maca', 'Pre-Sport Gel - Cacao/Maca', 'Citrus Peel', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_post_sport_recovery_gel', 'Post-Sport Recovery Gel', 'Turmeric', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_post_sport_recovery_gel', 'Post-Sport Recovery Gel', 'Rosehip', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_post_sport_recovery_gel', 'Post-Sport Recovery Gel', 'Nettle', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_post_sport_recovery_gel', 'Post-Sport Recovery Gel', 'Ginger', 'botanical_candidate', 'bot_ginger_wild_or_garden', 'Ginger (wild or garden)', 'matched_unique', 'bot_ginger_wild_or_garden:Ginger (wild or garden)', FALSE),
  ('prod_night_calm_gel_rose_ashwagandha', 'Night Calm Gel - Rose/Ashwagandha', 'Rose Petals', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_night_calm_gel_rose_ashwagandha', 'Night Calm Gel - Rose/Ashwagandha', 'Ashwagandha', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_night_calm_gel_rose_ashwagandha', 'Night Calm Gel - Rose/Ashwagandha', 'Lemon Balm', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_aphrodisiac_gel_damiana_rose', 'Aphrodisiac Gel - Damiana/Rose', 'Damiana', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_aphrodisiac_gel_damiana_rose', 'Aphrodisiac Gel - Damiana/Rose', 'Rose Petals', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_aphrodisiac_gel_damiana_rose', 'Aphrodisiac Gel - Damiana/Rose', 'Vanilla (extract)', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_scoby_fruit_leather_raspberry_hibiscus', 'SCOBY Fruit Leather - Raspberry/Hibiscus', 'Raspberry', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_scoby_fruit_leather_raspberry_hibiscus', 'SCOBY Fruit Leather - Raspberry/Hibiscus', 'Hibiscus', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_scoby_sour_strips', 'SCOBY Sour Strips', 'Citric acid', 'non_botanical', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_scoby_sour_strips', 'SCOBY Sour Strips', 'Berry powders', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_enzyme_bitters_gentian_koji', 'Enzyme Bitters - Gentian/Koji', 'Gentian', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_enzyme_bitters_gentian_koji', 'Enzyme Bitters - Gentian/Koji', 'Angelica', 'botanical_candidate', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE),
  ('prod_enzyme_bitters_gentian_koji', 'Enzyme Bitters - Gentian/Koji', 'Koji rice', 'non_botanical', NULL, NULL, 'unmatched_or_non_botanical', NULL, TRUE)
ON CONFLICT (product_id, ingredient_label) DO UPDATE SET
  ingredient_kind = EXCLUDED.ingredient_kind,
  botanical_entry_id = EXCLUDED.botanical_entry_id,
  matched_botanical_name = EXCLUDED.matched_botanical_name,
  match_status = EXCLUDED.match_status,
  candidate_matches = EXCLUDED.candidate_matches,
  resolution_needed = EXCLUDED.resolution_needed;
