-- Botanical database schema aligned to database_builder_actual_tables_only.xlsx
-- This version is intentionally "actual tables only".
-- It preserves the catalogue layer and keeps unresolved joins visible instead of inventing data.

CREATE TABLE IF NOT EXISTS raw_botanical_list (
  source_row INTEGER PRIMARY KEY,
  botanical_name TEXT NOT NULL,
  part_used TEXT,
  season TEXT,
  ferment_safety TEXT,
  use_type TEXT,
  functions TEXT,
  form_in_system TEXT,
  micronutrients TEXT,
  notes TEXT,
  ayurvedic_profile TEXT,
  tcm_meridians TEXT,
  tcm_nature_flavour TEXT,
  archetype_animal TEXT,
  scientific_actions TEXT,
  synergy_tags TEXT,
  element_planet TEXT,
  permaculture_guild TEXT,
  biodynamic_timing TEXT,
  soil_type TEXT,
  growing_conditions TEXT,
  foraging_habitat TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw_growing_harvesting (
  source_row INTEGER PRIMARY KEY,
  botanical_link TEXT NOT NULL,
  common_names TEXT,
  growth_habit TEXT,
  forest_garden_layer TEXT,
  lifespan TEXT,
  native_region TEXT,
  climate_band_prefers TEXT,
  hardiness_class TEXT,
  outdoor_suitability TEXT,
  greenhouse_zone TEXT,
  indoor_container_use TEXT,
  soil_type TEXT,
  soil_moisture TEXT,
  soil_functions TEXT,
  sun_exposure TEXT,
  humidity_preference TEXT,
  root_depth_type TEXT,
  spread_pattern TEXT,
  companion_plants TEXT,
  incompatible_with TEXT,
  guild_roles TEXT,
  foraging_habitat TEXT,
  harvest_window TEXT,
  planting_sowing_window TEXT,
  yield_regrowth TEXT,
  propagation_methods TEXT,
  conservation_status TEXT,
  foraging_cautions TEXT,
  wildlife_supported TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw_product_catalogue (
  source_row INTEGER PRIMARY KEY,
  product_name TEXT NOT NULL,
  format_label TEXT,
  function_label TEXT,
  core_base TEXT,
  protocols_used TEXT,
  botanicals_used TEXT,
  live_status TEXT,
  intended_use TEXT,
  strength_level TEXT,
  shelf_stability TEXT,
  development_status TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS raw_brew_ferment_protocols (
  source_row INTEGER PRIMARY KEY,
  protocol_name TEXT NOT NULL,
  stage TEXT,
  batch_size_l TEXT,
  tea_ratio_g_l TEXT,
  sugar_honey_g_l TEXT,
  culture_pct_vv TEXT,
  target_temp_c TEXT,
  ferment_time_days TEXT,
  output_form TEXT,
  live_cultures TEXT,
  intended_next_step TEXT,
  linked_product_use TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS branch_nodes (
  branch_id TEXT PRIMARY KEY,
  parent_branch_id TEXT REFERENCES branch_nodes(branch_id),
  branch_name TEXT NOT NULL,
  branch_slug TEXT NOT NULL UNIQUE,
  branch_scope_type TEXT NOT NULL,
  branch_status TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ferment_family (
  ferment_family_id TEXT PRIMARY KEY,
  ferment_family_name TEXT NOT NULL,
  status TEXT NOT NULL,
  sweetener_base_current_export TEXT,
  tea_base_current_export TEXT,
  target_temp_c_current_export TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS botanical_entries_master (
  botanical_entry_id TEXT PRIMARY KEY,
  common_name_pt TEXT,
  botanical_name TEXT NOT NULL,
  scientific_name TEXT,
  variety_cultivar TEXT,
  alternative_names TEXT,
  duplicate_name_group TEXT,
  duplicate_name_count INTEGER,
  part_used TEXT,
  season TEXT,
  ferment_safety TEXT,
  use_type TEXT,
  functions TEXT,
  form_in_system TEXT,
  micronutrients TEXT,
  notes TEXT,
  ayurvedic_profile TEXT,
  tcm_meridians TEXT,
  tcm_nature_flavour TEXT,
  archetype_animal TEXT,
  scientific_actions TEXT,
  synergy_tags TEXT,
  element_planet TEXT,
  permaculture_guild TEXT,
  biodynamic_timing TEXT,
  soil_type TEXT,
  growing_conditions TEXT,
  foraging_habitat TEXT,
  plant_type TEXT,
  perennial_main_group TEXT,
  sweep_bucket TEXT,
  scarcity_class TEXT,
  conservation_relevance TEXT,
  heritage_flag BOOLEAN,
  medicinal_flag BOOLEAN,
  ecological_value_flag BOOLEAN,
  perennial_rating INTEGER,
  inclusion_rationale TEXT,
  mature_height_m NUMERIC,
  mature_spread_m NUMERIC,
  size_class TEXT,
  root_volume_class TEXT,
  container_suitable TEXT,
  pruning_response TEXT,
  dwarf_flag BOOLEAN,
  grafted_flag BOOLEAN,
  self_fertile_flag BOOLEAN,
  pollination_requirement TEXT,
  pollinator_type TEXT,
  pollination_notes TEXT,
  plant_lifespan_years NUMERIC,
  productive_lifespan_years NUMERIC,
  replacement_cycle_years NUMERIC,
  data_confidence_level TEXT,
  data_source_type TEXT,
  record_completeness_score NUMERIC,
  fields_completed_count INTEGER,
  system_roles TEXT,
  propagation_difficulty TEXT,
  propagation_success_rate NUMERIC,
  invasiveness_risk_level TEXT,
  spread_control_required BOOLEAN,
  min_temp_c NUMERIC,
  max_temp_c NUMERIC,
  drought_tolerance TEXT,
  frost_tolerance TEXT,
  kombucha_1f_friendly_flag BOOLEAN,
  tea_friendly_flag BOOLEAN,
  bitters_friendly_flag BOOLEAN,
  cordial_friendly_flag BOOLEAN,
  fresh_produce_friendly_flag BOOLEAN,
  preserve_friendly_flag BOOLEAN,
  cosmetic_friendly_flag BOOLEAN,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS botanical_zone_profiles (
  zone_profile_id TEXT PRIMARY KEY,
  botanical_entry_id TEXT REFERENCES botanical_entries_master(botanical_entry_id),
  match_status TEXT NOT NULL,
  match_candidates TEXT,
  botanical_link TEXT NOT NULL,
  common_names TEXT,
  growth_habit TEXT,
  forest_garden_layer TEXT,
  lifespan TEXT,
  native_region TEXT,
  climate_band_prefers TEXT,
  hardiness_class TEXT,
  outdoor_suitability TEXT,
  greenhouse_zone TEXT,
  indoor_container_use TEXT,
  soil_type TEXT,
  soil_moisture TEXT,
  soil_functions TEXT,
  sun_exposure TEXT,
  humidity_preference TEXT,
  root_depth_type TEXT,
  spread_pattern TEXT,
  companion_plants TEXT,
  incompatible_with TEXT,
  guild_roles TEXT,
  foraging_habitat TEXT,
  harvest_window TEXT,
  planting_sowing_window TEXT,
  yield_regrowth TEXT,
  propagation_methods TEXT,
  conservation_status TEXT,
  foraging_cautions TEXT,
  wildlife_supported TEXT,
  notes TEXT,
  branch_id TEXT REFERENCES branch_nodes(branch_id),
  branch_fit TEXT,
  country TEXT,
  region TEXT,
  state_province TEXT,
  zone TEXT,
  microclimate_tags TEXT,
  production_mode TEXT,
  production_mode_basis TEXT,
  spacing_in_row_m NUMERIC,
  spacing_between_rows_m NUMERIC,
  spacing_notes TEXT,
  recommended_establishment_method TEXT,
  recommended_training_method TEXT,
  season_start_month INTEGER,
  season_end_month INTEGER,
  harvest_granularity TEXT,
  harvest_window_1_start TEXT,
  harvest_window_1_end TEXT,
  harvest_window_1_peak_start TEXT,
  harvest_window_1_peak_end TEXT,
  harvest_window_2_start TEXT,
  harvest_window_2_end TEXT,
  harvest_window_2_peak_start TEXT,
  harvest_window_2_peak_end TEXT,
  harvest_passes_per_year INTEGER,
  time_to_first_harvest TEXT,
  time_to_full_production TEXT,
  yield_output_type TEXT,
  yield_unit TEXT,
  area_harvested_ha NUMERIC,
  production_qty NUMERIC,
  average_yield_per_ha NUMERIC,
  yield_per_plant NUMERIC,
  yield_low NUMERIC,
  yield_typical NUMERIC,
  yield_high NUMERIC,
  processing_recovery_pct NUMERIC,
  production_value_brl NUMERIC,
  harvest_source TEXT,
  harvest_source_year INTEGER,
  harvest_confidence TEXT,
  yield_source TEXT,
  yield_source_year INTEGER,
  yield_confidence TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS botanical_product_paths (
  product_path_id TEXT PRIMARY KEY,
  botanical_entry_id TEXT NOT NULL REFERENCES botanical_entries_master(botanical_entry_id) ON DELETE CASCADE,
  product_family_tags TEXT,
  product_angle_notes TEXT,
  kombucha_1f_friendly BOOLEAN,
  bitters_friendly BOOLEAN,
  cordial_friendly BOOLEAN,
  tea_friendly BOOLEAN,
  fresh_produce_friendly BOOLEAN,
  preserve_friendly BOOLEAN,
  cosmetic_friendly BOOLEAN,
  edible_flower_friendly BOOLEAN,
  cut_flower_friendly BOOLEAN,
  medicinal_flower_friendly BOOLEAN,
  petal_flavour_friendly BOOLEAN,
  dried_floral_friendly BOOLEAN,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS protocol_library (
  protocol_id TEXT PRIMARY KEY,
  protocol_name TEXT NOT NULL,
  protocol_family TEXT REFERENCES ferment_family(ferment_family_id),
  stage TEXT,
  batch_size_l TEXT,
  tea_ratio_g_l TEXT,
  sugar_honey_g_l TEXT,
  culture_pct_vv TEXT,
  target_temp_c TEXT,
  ferment_time_days TEXT,
  output_form TEXT,
  live_cultures TEXT,
  intended_next_step TEXT,
  linked_product_use TEXT,
  notes TEXT,
  target_temp_c_min NUMERIC,
  target_temp_c_max NUMERIC,
  tea_ratio_g_l_min NUMERIC,
  tea_ratio_g_l_max NUMERIC,
  sugar_honey_g_l_min NUMERIC,
  sugar_honey_g_l_max NUMERIC,
  culture_pct_vv_min NUMERIC,
  culture_pct_vv_max NUMERIC,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS companion_guilds (
  guild_id TEXT PRIMARY KEY,
  guild_name TEXT NOT NULL,
  guild_scope TEXT,
  description TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS botanical_companion_rules (
  companion_rule_id TEXT PRIMARY KEY,
  botanical_entry_id TEXT NOT NULL REFERENCES botanical_entries_master(botanical_entry_id) ON DELETE CASCADE,
  companion_botanical_entry_id TEXT REFERENCES botanical_entries_master(botanical_entry_id),
  guild_id TEXT REFERENCES companion_guilds(guild_id),
  relation_type TEXT,
  compatibility_strength INTEGER,
  rule_basis TEXT,
  notes TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS species_root_profile (
  root_profile_id TEXT PRIMARY KEY,
  botanical_entry_id TEXT NOT NULL REFERENCES botanical_entries_master(botanical_entry_id) ON DELETE CASCADE,
  root_form TEXT,
  root_depth_class TEXT,
  root_spread_class TEXT,
  root_aggression TEXT,
  root_depth_min_m NUMERIC,
  root_depth_max_m NUMERIC,
  root_architecture_type TEXT,
  root_depth_category TEXT,
  excavation_sensitivity TEXT,
  root_competition_intensity TEXT,
  container_root_behavior TEXT,
  waterlogging_tolerance TEXT,
  notes TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS species_symbiosis_profile (
  symbiosis_profile_id TEXT PRIMARY KEY,
  botanical_entry_id TEXT NOT NULL REFERENCES botanical_entries_master(botanical_entry_id) ON DELETE CASCADE,
  symbiosis_type TEXT,
  symbiotic_partner_type TEXT,
  symbiotic_partner_botanical_id TEXT REFERENCES botanical_entries_master(botanical_entry_id),
  mycorrhizal_association_type TEXT,
  nitrogen_fixing_flag BOOLEAN,
  host_dependency_flag BOOLEAN,
  nurse_plant_flag BOOLEAN,
  rhizosphere_benefit_notes TEXT,
  symbiosis_strength TEXT,
  symbiosis_confidence TEXT,
  symbiotic_role_tags TEXT,
  notes TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS species_container_profile (
  container_profile_id TEXT PRIMARY KEY,
  botanical_entry_id TEXT NOT NULL REFERENCES botanical_entries_master(botanical_entry_id) ON DELETE CASCADE,
  container_suitable TEXT,
  container_permanence_class TEXT,
  transplant_ok BOOLEAN,
  notes TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS species_social_safety_profile (
  social_safety_profile_id TEXT PRIMARY KEY,
  botanical_entry_id TEXT NOT NULL REFERENCES botanical_entries_master(botanical_entry_id) ON DELETE CASCADE,
  toxicity_flag BOOLEAN,
  child_safe_flag BOOLEAN,
  allergen_risk TEXT,
  maintenance_level TEXT,
  notes TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS species_fauna_profile (
  fauna_profile_id TEXT PRIMARY KEY,
  botanical_entry_id TEXT NOT NULL REFERENCES botanical_entries_master(botanical_entry_id) ON DELETE CASCADE,
  bee_value TEXT,
  bird_value TEXT,
  bat_value TEXT,
  wildlife_support TEXT,
  notes TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS species_governance_profile (
  governance_profile_id TEXT PRIMARY KEY,
  botanical_entry_id TEXT NOT NULL REFERENCES botanical_entries_master(botanical_entry_id) ON DELETE CASCADE,
  native_status TEXT,
  restoration_allowed BOOLEAN,
  experimental_only BOOLEAN,
  release_prohibited BOOLEAN,
  protected_area_allowed BOOLEAN,
  notes TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS species_substrate_profile (
  substrate_profile_id TEXT PRIMARY KEY,
  botanical_entry_id TEXT NOT NULL REFERENCES botanical_entries_master(botanical_entry_id) ON DELETE CASCADE,
  soil_preference TEXT,
  amendment_compatibility TEXT,
  mycelium_support BOOLEAN,
  biochar_ok BOOLEAN,
  soil_regeneration_value TEXT,
  notes TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS species_design_matrix (
  design_matrix_id TEXT PRIMARY KEY,
  botanical_entry_id TEXT NOT NULL REFERENCES botanical_entries_master(botanical_entry_id) ON DELETE CASCADE,
  food_forest_layer TEXT,
  canonical_layer_primary TEXT,
  canonical_layer_secondary TEXT,
  layer_stack_tags TEXT,
  guild_role TEXT,
  shade_tolerance TEXT,
  water_need TEXT,
  companion_tags TEXT,
  notes TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS module_guild_profiles (
  module_guild_profile_id TEXT PRIMARY KEY,
  module_name TEXT NOT NULL,
  module_scope TEXT,
  description TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS addon_library (
  addon_id TEXT PRIMARY KEY,
  addon_name TEXT NOT NULL,
  addon_category TEXT,
  description TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS hons_overlay (
  hons_overlay_id TEXT PRIMARY KEY,
  botanical_entry_id TEXT REFERENCES botanical_entries_master(botanical_entry_id),
  related_entity_id TEXT,
  ownership_model TEXT,
  rights_notes TEXT,
  stage TEXT,
  attribution TEXT,
  governance_notes TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_catalogue (
  product_id TEXT PRIMARY KEY,
  product_name TEXT NOT NULL,
  catalogue_line_guess TEXT,
  fermentation_family_guess TEXT REFERENCES ferment_family(ferment_family_id),
  format_label TEXT,
  function_label TEXT,
  core_base TEXT,
  protocols_used TEXT,
  botanicals_used TEXT,
  live_status TEXT,
  intended_use TEXT,
  strength_level TEXT,
  shelf_stability TEXT,
  development_status TEXT,
  notes TEXT,
  source_table TEXT,
  source_row INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_protocol_links (
  product_id TEXT NOT NULL REFERENCES product_catalogue(product_id) ON DELETE CASCADE,
  product_name TEXT NOT NULL,
  protocol_ref_label TEXT NOT NULL,
  protocol_id TEXT REFERENCES protocol_library(protocol_id),
  matched_protocol_name TEXT,
  match_status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (product_id, protocol_ref_label)
);

CREATE TABLE IF NOT EXISTS product_botanical_links (
  product_id TEXT NOT NULL REFERENCES product_catalogue(product_id) ON DELETE CASCADE,
  product_name TEXT NOT NULL,
  ingredient_label TEXT NOT NULL,
  ingredient_kind TEXT NOT NULL,
  botanical_entry_id TEXT REFERENCES botanical_entries_master(botanical_entry_id),
  matched_botanical_name TEXT,
  match_status TEXT NOT NULL,
  candidate_matches TEXT,
  resolution_needed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (product_id, ingredient_label)
);

CREATE OR REPLACE VIEW current_product_line_summary AS
SELECT
  pc.product_id,
  pc.product_name,
  pc.core_base,
  pc.catalogue_line_guess,
  pc.fermentation_family_guess,
  pc.format_label AS format,
  pc.development_status,
  COUNT(ppl.protocol_ref_label) AS linked_protocol_count,
  STRING_AGG(COALESCE(ppl.matched_protocol_name, ppl.protocol_ref_label), '; ' ORDER BY ppl.protocol_ref_label) AS linked_protocol_names,
  STRING_AGG(DISTINCT NULLIF(pl.sugar_honey_g_l, ''), '; ') AS sweetener_base_from_linked_protocols,
  STRING_AGG(DISTINCT NULLIF(pl.tea_ratio_g_l, ''), '; ') AS tea_ratio_from_linked_protocols,
  MIN(pl.target_temp_c_min) AS target_temp_c_min,
  MAX(pl.target_temp_c_max) AS target_temp_c_max,
  pc.live_status AS live_culture_state,
  'shared_family_ok_if_differentiated'::TEXT AS merge_rule,
  'Current export proves Jun-related product logic; do not collapse into indistinguishable Kombucha rows.'::TEXT AS builder_note
FROM product_catalogue pc
LEFT JOIN product_protocol_links ppl
  ON ppl.product_id = pc.product_id
LEFT JOIN protocol_library pl
  ON pl.protocol_id = ppl.protocol_id
GROUP BY
  pc.product_id,
  pc.product_name,
  pc.core_base,
  pc.catalogue_line_guess,
  pc.fermentation_family_guess,
  pc.format_label,
  pc.development_status,
  pc.live_status;

CREATE OR REPLACE VIEW protocol_gap_report AS
SELECT
  product_id,
  product_name,
  protocol_ref_label,
  protocol_id,
  matched_protocol_name,
  match_status
FROM product_protocol_links
WHERE match_status <> 'matched';

CREATE OR REPLACE VIEW botanical_gap_report AS
SELECT
  product_id,
  product_name,
  ingredient_label,
  ingredient_kind,
  botanical_entry_id,
  matched_botanical_name,
  match_status,
  candidate_matches
FROM product_botanical_links
WHERE match_status <> 'matched_unique';

CREATE OR REPLACE VIEW "Botanical_Operational_View" AS
SELECT
  bem.botanical_entry_id AS "Botanical Entry ID",
  bem.common_name_pt AS "Common Name (PT)",
  bem.botanical_name AS "Common Name (EN)",
  bem.alternative_names AS "Alternative Names",
  bem.scientific_name AS "Scientific Name",
  bem.variety_cultivar AS "Variety / Cultivar",
  COALESCE(bem.plant_type, bem.form_in_system) AS "Plant Type",
  bem.perennial_main_group AS "Perennial_Main_Group",
  bem.sweep_bucket AS "Sweep_Bucket",
  bem.scarcity_class AS "Scarcity_Class",
  bem.conservation_relevance AS "Conservation_Relevance",
  bem.heritage_flag AS "Heritage_Flag",
  bem.medicinal_flag AS "Medicinal_Flag",
  bem.ecological_value_flag AS "Ecological_Value_Flag",
  bem.perennial_rating AS "Perennial_Rating",
  bem.inclusion_rationale AS "Inclusion_Rationale",
  bem.mature_height_m AS "Mature_Height_m",
  bem.mature_spread_m AS "Mature_Spread_m",
  bem.size_class AS "Size_Class",
  bem.root_volume_class AS "Root_Volume_Class",
  bem.container_suitable AS "Container_Suitable",
  bem.pruning_response AS "Pruning_Response",
  bem.dwarf_flag AS "Dwarf_Flag",
  bem.grafted_flag AS "Grafted_Flag",
  bem.self_fertile_flag AS "Self_Fertile_Flag",
  bem.pollination_requirement AS "Pollination Requirement",
  bem.pollinator_type AS "Pollinator Type",
  bem.pollination_notes AS "Pollination Notes",
  bem.plant_lifespan_years AS "Plant Lifespan Years",
  bem.productive_lifespan_years AS "Productive Lifespan Years",
  bem.replacement_cycle_years AS "Replacement Cycle Years",
  bem.data_confidence_level AS "Data Confidence Level",
  bem.data_source_type AS "Data Source Type",
  bem.record_completeness_score AS "Record Completeness Score",
  bem.fields_completed_count AS "Fields Completed Count",
  bem.system_roles AS "System Roles",
  bem.propagation_difficulty AS "Propagation Difficulty",
  bem.propagation_success_rate AS "Propagation Success Rate",
  bem.invasiveness_risk_level AS "Invasiveness Risk Level",
  bem.spread_control_required AS "Spread Control Required",
  bem.min_temp_c AS "Min Temp C",
  bem.max_temp_c AS "Max Temp C",
  bem.drought_tolerance AS "Drought Tolerance",
  bem.frost_tolerance AS "Frost Tolerance",
  bn.branch_name AS "Branch",
  bn.branch_scope_type AS "Branch Scope Type",
  bzp.branch_fit AS "Branch_Fit",
  bzp.country AS "Country",
  bzp.region AS "Region",
  bzp.state_province AS "State / Province",
  bzp.zone AS "Zone",
  bzp.microclimate_tags AS "Microclimate Tags",
  bzp.production_mode AS "Production Mode",
  bzp.production_mode_basis AS "Production Mode Basis",
  bzp.spacing_in_row_m AS "Spacing In Row M",
  bzp.spacing_between_rows_m AS "Spacing Between Rows M",
  bzp.spacing_notes AS "Spacing Notes",
  bzp.recommended_establishment_method AS "Recommended Establishment Method",
  bzp.recommended_training_method AS "Recommended Training Method",
  bzp.season_start_month AS "Season Start Month",
  bzp.season_end_month AS "Season End Month",
  bem.kombucha_1f_friendly_flag AS "Kombucha_1F_Friendly",
  bem.tea_friendly_flag AS "Tea Friendly",
  bem.bitters_friendly_flag AS "Bitters Friendly",
  bem.cordial_friendly_flag AS "Cordial Friendly",
  bem.fresh_produce_friendly_flag AS "Fresh Produce Friendly",
  bem.preserve_friendly_flag AS "Preserve Friendly",
  bem.cosmetic_friendly_flag AS "Cosmetic Friendly",
  bzp.harvest_granularity AS "Harvest Granularity",
  bzp.harvest_window_1_start AS "Harvest Window 1 Start",
  bzp.harvest_window_1_end AS "Harvest Window 1 End",
  bzp.harvest_window_1_peak_start AS "Harvest Window 1 Peak Start",
  bzp.harvest_window_1_peak_end AS "Harvest Window 1 Peak End",
  bzp.harvest_window_2_start AS "Harvest Window 2 Start",
  bzp.harvest_window_2_end AS "Harvest Window 2 End",
  bzp.harvest_window_2_peak_start AS "Harvest Window 2 Peak Start",
  bzp.harvest_window_2_peak_end AS "Harvest Window 2 Peak End",
  bzp.harvest_passes_per_year AS "Harvest Passes Per Year",
  bzp.time_to_first_harvest AS "Time To First Harvest",
  bzp.time_to_full_production AS "Time To Full Production",
  bzp.harvest_window AS "Harvest Window",
  bzp.planting_sowing_window AS "Planting / Sowing Window",
  bzp.yield_regrowth AS "Yield & Regrowth",
  bzp.yield_output_type AS "Yield Output Type",
  bzp.yield_unit AS "Yield Unit",
  bzp.area_harvested_ha AS "Area Harvested Ha",
  bzp.production_qty AS "Production Qty",
  bzp.average_yield_per_ha AS "Average Yield Per Ha",
  bzp.yield_per_plant AS "Yield Per Plant",
  bzp.yield_low AS "Yield Low",
  bzp.yield_typical AS "Yield Typical",
  bzp.yield_high AS "Yield High",
  bzp.processing_recovery_pct AS "Processing Recovery Pct",
  bzp.production_value_brl AS "Production Value BRL",
  bzp.harvest_source AS "Harvest Source",
  bzp.harvest_source_year AS "Harvest Source Year",
  bzp.harvest_confidence AS "Harvest Confidence",
  bzp.yield_source AS "Yield Source",
  bzp.yield_source_year AS "Yield Source Year",
  bzp.yield_confidence AS "Yield Confidence",
  bzp.propagation_methods AS "Propagation Methods",
  bzp.conservation_status AS "Conservation Status",
  bzp.wildlife_supported AS "Wildlife Supported",
  bzp.notes AS "Notes"
FROM botanical_entries_master bem
LEFT JOIN botanical_zone_profiles bzp
  ON bzp.botanical_entry_id = bem.botanical_entry_id
LEFT JOIN branch_nodes bn
  ON bn.branch_id = bzp.branch_id;
