-- Auto-generated from Notion schemas for currently missing Supabase target tables
-- Generated: 2026-03-05T00:38:59.171016+00:00

CREATE TABLE IF NOT EXISTS "stage_to_canonical_tracker_stage" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notion_page_id" TEXT UNIQUE,
  "order" REAL,
  "notes" TEXT,
  "ready" BOOLEAN,
  "completed" BOOLEAN,
  "phase" TEXT,
  "blocked" BOOLEAN,
  "stage_table" TEXT,
  "status" TEXT,
  "sql_file" TEXT,
  "task" TEXT
);
